# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

class CapPeriod(object):
    unknown = 0
    session = 1
    day = 2
    week = 3
    month = 4
    lifetime = 5
