# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class ContentLink(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 16

    # ContentLink
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ContentLink
    def MessageBlockIdx(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # ContentLink
    def UiPathIdx(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # ContentLink
    def PromotionIdx(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # ContentLink
    def ContentPayloadSourceId(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateContentLink(builder, messageBlockIdx, uiPathIdx, promotionIdx, contentPayloadSourceId):
    builder.Prep(4, 16)
    builder.PrependUint32(contentPayloadSourceId)
    builder.PrependUint32(promotionIdx)
    builder.PrependUint32(uiPathIdx)
    builder.PrependUint32(messageBlockIdx)
    return builder.Offset()
