from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ContentPromotion(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ContentPromotion: ...
  @classmethod
  def GetRootAsContentPromotion(cls, buf: bytes, offset: int) -> ContentPromotion: ...
  @classmethod
  def ContentPromotionBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceId(self) -> int: ...
  def Name(self) -> int: ...
  def Discount(self) -> int: ...
  def Type(self) -> int: ...
  def Status(self) -> int: ...
def ContentPromotionStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ContentPromotionAddSourceId(builder: flatbuffers.Builder, sourceId: int) -> None: ...
def ContentPromotionAddName(builder: flatbuffers.Builder, name: int) -> None: ...
def ContentPromotionAddDiscount(builder: flatbuffers.Builder, discount: int) -> None: ...
def ContentPromotionAddType(builder: flatbuffers.Builder, type: int) -> None: ...
def ContentPromotionAddStatus(builder: flatbuffers.Builder, status: int) -> None: ...
def ContentPromotionEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

