# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class ContentPromotion(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ContentPromotion()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsContentPromotion(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ContentPromotionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # ContentPromotion
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ContentPromotion
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ContentPromotion
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ContentPromotion
    def Discount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ContentPromotion
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ContentPromotion
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ContentPromotionStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    ContentPromotionStart(builder)

def ContentPromotionAddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUint32Slot(0, sourceId, 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    ContentPromotionAddSourceId(builder, sourceId)

def ContentPromotionAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUint32Slot(1, name, 0)

def AddName(builder: flatbuffers.Builder, name: int):
    ContentPromotionAddName(builder, name)

def ContentPromotionAddDiscount(builder: flatbuffers.Builder, discount: int):
    builder.PrependUint32Slot(2, discount, 0)

def AddDiscount(builder: flatbuffers.Builder, discount: int):
    ContentPromotionAddDiscount(builder, discount)

def ContentPromotionAddType(builder: flatbuffers.Builder, type: int):
    builder.PrependUint32Slot(3, type, 0)

def AddType(builder: flatbuffers.Builder, type: int):
    ContentPromotionAddType(builder, type)

def ContentPromotionAddStatus(builder: flatbuffers.Builder, status: int):
    builder.PrependUint32Slot(4, status, 0)

def AddStatus(builder: flatbuffers.Builder, status: int):
    ContentPromotionAddStatus(builder, status)

def ContentPromotionEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ContentPromotionEnd(builder)
