# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class ContentUiPath(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ContentUiPath()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsContentUiPath(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ContentUiPathBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # ContentUiPath
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ContentUiPath
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ContentUiPath
    def ActionType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ContentUiPath
    def PlanHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ContentUiPath
    def PromotionIdx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ContentUiPath
    def PlacementHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ContentUiPath
    def Url(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ContentUiPath
    def TourId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ContentUiPath
    def TargetBillingPeriod(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ContentUiPath
    def Description(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ContentUiPathStart(builder: flatbuffers.Builder):
    builder.StartObject(9)

def Start(builder: flatbuffers.Builder):
    ContentUiPathStart(builder)

def ContentUiPathAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUint32Slot(0, name, 0)

def AddName(builder: flatbuffers.Builder, name: int):
    ContentUiPathAddName(builder, name)

def ContentUiPathAddActionType(builder: flatbuffers.Builder, actionType: int):
    builder.PrependUint8Slot(1, actionType, 0)

def AddActionType(builder: flatbuffers.Builder, actionType: int):
    ContentUiPathAddActionType(builder, actionType)

def ContentUiPathAddPlanHandle(builder: flatbuffers.Builder, planHandle: int):
    builder.PrependUint32Slot(2, planHandle, 0)

def AddPlanHandle(builder: flatbuffers.Builder, planHandle: int):
    ContentUiPathAddPlanHandle(builder, planHandle)

def ContentUiPathAddPromotionIdx(builder: flatbuffers.Builder, promotionIdx: int):
    builder.PrependUint32Slot(3, promotionIdx, 0)

def AddPromotionIdx(builder: flatbuffers.Builder, promotionIdx: int):
    ContentUiPathAddPromotionIdx(builder, promotionIdx)

def ContentUiPathAddPlacementHandle(builder: flatbuffers.Builder, placementHandle: int):
    builder.PrependUint32Slot(4, placementHandle, 0)

def AddPlacementHandle(builder: flatbuffers.Builder, placementHandle: int):
    ContentUiPathAddPlacementHandle(builder, placementHandle)

def ContentUiPathAddUrl(builder: flatbuffers.Builder, url: int):
    builder.PrependUint32Slot(5, url, 0)

def AddUrl(builder: flatbuffers.Builder, url: int):
    ContentUiPathAddUrl(builder, url)

def ContentUiPathAddTourId(builder: flatbuffers.Builder, tourId: int):
    builder.PrependUint32Slot(6, tourId, 0)

def AddTourId(builder: flatbuffers.Builder, tourId: int):
    ContentUiPathAddTourId(builder, tourId)

def ContentUiPathAddTargetBillingPeriod(builder: flatbuffers.Builder, targetBillingPeriod: int):
    builder.PrependUint8Slot(7, targetBillingPeriod, 0)

def AddTargetBillingPeriod(builder: flatbuffers.Builder, targetBillingPeriod: int):
    ContentUiPathAddTargetBillingPeriod(builder, targetBillingPeriod)

def ContentUiPathAddDescription(builder: flatbuffers.Builder, description: int):
    builder.PrependUint32Slot(8, description, 0)

def AddDescription(builder: flatbuffers.Builder, description: int):
    ContentUiPathAddDescription(builder, description)

def ContentUiPathEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ContentUiPathEnd(builder)
