from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.BillingPeriod import BillingPeriod
from revturbine.bundle.UiPathActionType import UiPathActionType

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ContentUiPath(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ContentUiPath: ...
  @classmethod
  def GetRootAsContentUiPath(cls, buf: bytes, offset: int) -> ContentUiPath: ...
  @classmethod
  def ContentUiPathBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Name(self) -> int: ...
  def ActionType(self) -> typing.Literal[UiPathActionType.unknown, UiPathActionType.open_checkout_modal, UiPathActionType.navigate_to_plans, UiPathActionType.open_upgrade_modal, UiPathActionType.open_placement, UiPathActionType.book_demo, UiPathActionType.open_feature_tour, UiPathActionType.extend_trial, UiPathActionType.switch_billing_period, UiPathActionType.custom_url, UiPathActionType.dismiss, UiPathActionType.contact_sales, UiPathActionType.complete_onboarding, UiPathActionType.invite_teammate, UiPathActionType.refer_friend, UiPathActionType.verify_work_email, UiPathActionType.update_payment_method, UiPathActionType.enable_auto_renewal, UiPathActionType.manage_subscription]: ...
  def PlanHandle(self) -> int: ...
  def PromotionIdx(self) -> int: ...
  def PlacementHandle(self) -> int: ...
  def Url(self) -> int: ...
  def TourId(self) -> int: ...
  def TargetBillingPeriod(self) -> typing.Literal[BillingPeriod.unknown, BillingPeriod.monthly, BillingPeriod.annual]: ...
  def Description(self) -> int: ...
def ContentUiPathStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ContentUiPathAddName(builder: flatbuffers.Builder, name: int) -> None: ...
def ContentUiPathAddActionType(builder: flatbuffers.Builder, actionType: typing.Literal[UiPathActionType.unknown, UiPathActionType.open_checkout_modal, UiPathActionType.navigate_to_plans, UiPathActionType.open_upgrade_modal, UiPathActionType.open_placement, UiPathActionType.book_demo, UiPathActionType.open_feature_tour, UiPathActionType.extend_trial, UiPathActionType.switch_billing_period, UiPathActionType.custom_url, UiPathActionType.dismiss, UiPathActionType.contact_sales, UiPathActionType.complete_onboarding, UiPathActionType.invite_teammate, UiPathActionType.refer_friend, UiPathActionType.verify_work_email, UiPathActionType.update_payment_method, UiPathActionType.enable_auto_renewal, UiPathActionType.manage_subscription]) -> None: ...
def ContentUiPathAddPlanHandle(builder: flatbuffers.Builder, planHandle: int) -> None: ...
def ContentUiPathAddPromotionIdx(builder: flatbuffers.Builder, promotionIdx: int) -> None: ...
def ContentUiPathAddPlacementHandle(builder: flatbuffers.Builder, placementHandle: int) -> None: ...
def ContentUiPathAddUrl(builder: flatbuffers.Builder, url: int) -> None: ...
def ContentUiPathAddTourId(builder: flatbuffers.Builder, tourId: int) -> None: ...
def ContentUiPathAddTargetBillingPeriod(builder: flatbuffers.Builder, targetBillingPeriod: typing.Literal[BillingPeriod.unknown, BillingPeriod.monthly, BillingPeriod.annual]) -> None: ...
def ContentUiPathAddDescription(builder: flatbuffers.Builder, description: int) -> None: ...
def ContentUiPathEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

