from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ContentLink(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def MessageBlockIdx(self) -> int: ...
  def UiPathIdx(self) -> int: ...
  def PromotionIdx(self) -> int: ...
  def ContentPayloadSourceId(self) -> int: ...

def CreateContentLink(builder: flatbuffers.Builder, messageBlockIdx: int, uiPathIdx: int, promotionIdx: int, contentPayloadSourceId: int) -> uoffset: ...

