# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class CreditsFields(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CreditsFields()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCreditsFields(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CreditsFieldsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # CreditsFields
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CreditsFields
    def Allowance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CreditsFields
    def Rollover(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CreditsFields
    def MaxRollover(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CreditsFields
    def MaxBalance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return -1

    # CreditsFields
    def InitialGrant(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return -1

    # CreditsFields
    def Enforcement(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def CreditsFieldsStart(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    CreditsFieldsStart(builder)

def CreditsFieldsAddAllowance(builder: flatbuffers.Builder, allowance: int):
    builder.PrependInt64Slot(0, allowance, 0)

def AddAllowance(builder: flatbuffers.Builder, allowance: int):
    CreditsFieldsAddAllowance(builder, allowance)

def CreditsFieldsAddRollover(builder: flatbuffers.Builder, rollover: bool):
    builder.PrependBoolSlot(1, rollover, 0)

def AddRollover(builder: flatbuffers.Builder, rollover: bool):
    CreditsFieldsAddRollover(builder, rollover)

def CreditsFieldsAddMaxRollover(builder: flatbuffers.Builder, maxRollover: int):
    builder.PrependInt64Slot(2, maxRollover, 0)

def AddMaxRollover(builder: flatbuffers.Builder, maxRollover: int):
    CreditsFieldsAddMaxRollover(builder, maxRollover)

def CreditsFieldsAddMaxBalance(builder: flatbuffers.Builder, maxBalance: int):
    builder.PrependInt64Slot(3, maxBalance, -1)

def AddMaxBalance(builder: flatbuffers.Builder, maxBalance: int):
    CreditsFieldsAddMaxBalance(builder, maxBalance)

def CreditsFieldsAddInitialGrant(builder: flatbuffers.Builder, initialGrant: int):
    builder.PrependInt64Slot(4, initialGrant, -1)

def AddInitialGrant(builder: flatbuffers.Builder, initialGrant: int):
    CreditsFieldsAddInitialGrant(builder, initialGrant)

def CreditsFieldsAddEnforcement(builder: flatbuffers.Builder, enforcement: int):
    builder.PrependUint8Slot(5, enforcement, 0)

def AddEnforcement(builder: flatbuffers.Builder, enforcement: int):
    CreditsFieldsAddEnforcement(builder, enforcement)

def CreditsFieldsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return CreditsFieldsEnd(builder)
