from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.Enforcement import Enforcement

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class CreditsFields(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> CreditsFields: ...
  @classmethod
  def GetRootAsCreditsFields(cls, buf: bytes, offset: int) -> CreditsFields: ...
  @classmethod
  def CreditsFieldsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Allowance(self) -> int: ...
  def Rollover(self) -> bool: ...
  def MaxRollover(self) -> int: ...
  def MaxBalance(self) -> int: ...
  def InitialGrant(self) -> int: ...
  def Enforcement(self) -> typing.Literal[Enforcement.unknown, Enforcement.hard_block, Enforcement.soft_warn, Enforcement.throttle, Enforcement.notify, Enforcement.soft_block, Enforcement.degrade, Enforcement.allow_overage]: ...
def CreditsFieldsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def CreditsFieldsAddAllowance(builder: flatbuffers.Builder, allowance: int) -> None: ...
def CreditsFieldsAddRollover(builder: flatbuffers.Builder, rollover: bool) -> None: ...
def CreditsFieldsAddMaxRollover(builder: flatbuffers.Builder, maxRollover: int) -> None: ...
def CreditsFieldsAddMaxBalance(builder: flatbuffers.Builder, maxBalance: int) -> None: ...
def CreditsFieldsAddInitialGrant(builder: flatbuffers.Builder, initialGrant: int) -> None: ...
def CreditsFieldsAddEnforcement(builder: flatbuffers.Builder, enforcement: typing.Literal[Enforcement.unknown, Enforcement.hard_block, Enforcement.soft_warn, Enforcement.throttle, Enforcement.notify, Enforcement.soft_block, Enforcement.degrade, Enforcement.allow_overage]) -> None: ...
def CreditsFieldsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

