from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class CtaConfig(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> CtaConfig: ...
  @classmethod
  def GetRootAsCtaConfig(cls, buf: bytes, offset: int) -> CtaConfig: ...
  @classmethod
  def CtaConfigBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Label(self) -> int: ...
  def Path(self) -> int: ...
  def ConfigKeys(self, i: int) -> typing.List[int]: ...
  def ConfigKeysAsNumpy(self) -> np.ndarray: ...
  def ConfigKeysLength(self) -> int: ...
  def ConfigKeysIsNone(self) -> bool: ...
  def ConfigValues(self, i: int) -> typing.List[int]: ...
  def ConfigValuesAsNumpy(self) -> np.ndarray: ...
  def ConfigValuesLength(self) -> int: ...
  def ConfigValuesIsNone(self) -> bool: ...
def CtaConfigStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def CtaConfigAddLabel(builder: flatbuffers.Builder, label: int) -> None: ...
def CtaConfigAddPath(builder: flatbuffers.Builder, path: int) -> None: ...
def CtaConfigAddConfigKeys(builder: flatbuffers.Builder, configKeys: uoffset) -> None: ...
def CtaConfigStartConfigKeysVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartConfigKeysVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def CtaConfigAddConfigValues(builder: flatbuffers.Builder, configValues: uoffset) -> None: ...
def CtaConfigStartConfigValuesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartConfigValuesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def CtaConfigEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

