# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class CtaConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CtaConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCtaConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CtaConfigBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # CtaConfig
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CtaConfig
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CtaConfig
    def Path(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CtaConfig
    def ConfigKeys(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # CtaConfig
    def ConfigKeysAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # CtaConfig
    def ConfigKeysLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CtaConfig
    def ConfigKeysIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # CtaConfig
    def ConfigValues(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # CtaConfig
    def ConfigValuesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # CtaConfig
    def ConfigValuesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CtaConfig
    def ConfigValuesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def CtaConfigStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    CtaConfigStart(builder)

def CtaConfigAddLabel(builder: flatbuffers.Builder, label: int):
    builder.PrependUint32Slot(0, label, 0)

def AddLabel(builder: flatbuffers.Builder, label: int):
    CtaConfigAddLabel(builder, label)

def CtaConfigAddPath(builder: flatbuffers.Builder, path: int):
    builder.PrependUint32Slot(1, path, 0)

def AddPath(builder: flatbuffers.Builder, path: int):
    CtaConfigAddPath(builder, path)

def CtaConfigAddConfigKeys(builder: flatbuffers.Builder, configKeys: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(configKeys), 0)

def AddConfigKeys(builder: flatbuffers.Builder, configKeys: int):
    CtaConfigAddConfigKeys(builder, configKeys)

def CtaConfigStartConfigKeysVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartConfigKeysVector(builder, numElems: int) -> int:
    return CtaConfigStartConfigKeysVector(builder, numElems)

def CtaConfigAddConfigValues(builder: flatbuffers.Builder, configValues: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(configValues), 0)

def AddConfigValues(builder: flatbuffers.Builder, configValues: int):
    CtaConfigAddConfigValues(builder, configValues)

def CtaConfigStartConfigValuesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartConfigValuesVector(builder, numElems: int) -> int:
    return CtaConfigStartConfigValuesVector(builder, numElems)

def CtaConfigEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return CtaConfigEnd(builder)
