from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class EnforcementDefault(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> EnforcementDefault: ...
  @classmethod
  def GetRootAsEnforcementDefault(cls, buf: bytes, offset: int) -> EnforcementDefault: ...
  @classmethod
  def EnforcementDefaultBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Handle(self) -> int: ...
  def EntitlementHandle(self) -> int: ...
  def SoftLimitPercent(self) -> int: ...
  def HardLimitPercent(self) -> int: ...
  def SoftLimitAction(self) -> int: ...
  def HardLimitAction(self) -> int: ...
  def GracePeriodHours(self) -> int: ...
  def NotificationChannels(self, i: int) -> typing.List[int]: ...
  def NotificationChannelsAsNumpy(self) -> np.ndarray: ...
  def NotificationChannelsLength(self) -> int: ...
  def NotificationChannelsIsNone(self) -> bool: ...
  def IsActive(self) -> bool: ...
def EnforcementDefaultStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def EnforcementDefaultAddHandle(builder: flatbuffers.Builder, handle: int) -> None: ...
def EnforcementDefaultAddEntitlementHandle(builder: flatbuffers.Builder, entitlementHandle: int) -> None: ...
def EnforcementDefaultAddSoftLimitPercent(builder: flatbuffers.Builder, softLimitPercent: int) -> None: ...
def EnforcementDefaultAddHardLimitPercent(builder: flatbuffers.Builder, hardLimitPercent: int) -> None: ...
def EnforcementDefaultAddSoftLimitAction(builder: flatbuffers.Builder, softLimitAction: int) -> None: ...
def EnforcementDefaultAddHardLimitAction(builder: flatbuffers.Builder, hardLimitAction: int) -> None: ...
def EnforcementDefaultAddGracePeriodHours(builder: flatbuffers.Builder, gracePeriodHours: int) -> None: ...
def EnforcementDefaultAddNotificationChannels(builder: flatbuffers.Builder, notificationChannels: uoffset) -> None: ...
def EnforcementDefaultStartNotificationChannelsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartNotificationChannelsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def EnforcementDefaultAddIsActive(builder: flatbuffers.Builder, isActive: bool) -> None: ...
def EnforcementDefaultEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

