# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

class Enforcement(object):
    unknown = 0
    hard_block = 1
    soft_warn = 2
    throttle = 3
    notify = 4
    soft_block = 5
    degrade = 6
    allow_overage = 7
