# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class EnforcementDefault(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EnforcementDefault()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEnforcementDefault(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EnforcementDefaultBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # EnforcementDefault
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EnforcementDefault
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EnforcementDefault
    def EntitlementHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EnforcementDefault
    def SoftLimitPercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EnforcementDefault
    def HardLimitPercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EnforcementDefault
    def SoftLimitAction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EnforcementDefault
    def HardLimitAction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EnforcementDefault
    def GracePeriodHours(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EnforcementDefault
    def NotificationChannels(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # EnforcementDefault
    def NotificationChannelsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # EnforcementDefault
    def NotificationChannelsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EnforcementDefault
    def NotificationChannelsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # EnforcementDefault
    def IsActive(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def EnforcementDefaultStart(builder: flatbuffers.Builder):
    builder.StartObject(9)

def Start(builder: flatbuffers.Builder):
    EnforcementDefaultStart(builder)

def EnforcementDefaultAddHandle(builder: flatbuffers.Builder, handle: int):
    builder.PrependUint32Slot(0, handle, 0)

def AddHandle(builder: flatbuffers.Builder, handle: int):
    EnforcementDefaultAddHandle(builder, handle)

def EnforcementDefaultAddEntitlementHandle(builder: flatbuffers.Builder, entitlementHandle: int):
    builder.PrependUint32Slot(1, entitlementHandle, 0)

def AddEntitlementHandle(builder: flatbuffers.Builder, entitlementHandle: int):
    EnforcementDefaultAddEntitlementHandle(builder, entitlementHandle)

def EnforcementDefaultAddSoftLimitPercent(builder: flatbuffers.Builder, softLimitPercent: int):
    builder.PrependInt64Slot(2, softLimitPercent, 0)

def AddSoftLimitPercent(builder: flatbuffers.Builder, softLimitPercent: int):
    EnforcementDefaultAddSoftLimitPercent(builder, softLimitPercent)

def EnforcementDefaultAddHardLimitPercent(builder: flatbuffers.Builder, hardLimitPercent: int):
    builder.PrependInt64Slot(3, hardLimitPercent, 0)

def AddHardLimitPercent(builder: flatbuffers.Builder, hardLimitPercent: int):
    EnforcementDefaultAddHardLimitPercent(builder, hardLimitPercent)

def EnforcementDefaultAddSoftLimitAction(builder: flatbuffers.Builder, softLimitAction: int):
    builder.PrependUint32Slot(4, softLimitAction, 0)

def AddSoftLimitAction(builder: flatbuffers.Builder, softLimitAction: int):
    EnforcementDefaultAddSoftLimitAction(builder, softLimitAction)

def EnforcementDefaultAddHardLimitAction(builder: flatbuffers.Builder, hardLimitAction: int):
    builder.PrependUint32Slot(5, hardLimitAction, 0)

def AddHardLimitAction(builder: flatbuffers.Builder, hardLimitAction: int):
    EnforcementDefaultAddHardLimitAction(builder, hardLimitAction)

def EnforcementDefaultAddGracePeriodHours(builder: flatbuffers.Builder, gracePeriodHours: int):
    builder.PrependInt64Slot(6, gracePeriodHours, 0)

def AddGracePeriodHours(builder: flatbuffers.Builder, gracePeriodHours: int):
    EnforcementDefaultAddGracePeriodHours(builder, gracePeriodHours)

def EnforcementDefaultAddNotificationChannels(builder: flatbuffers.Builder, notificationChannels: int):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(notificationChannels), 0)

def AddNotificationChannels(builder: flatbuffers.Builder, notificationChannels: int):
    EnforcementDefaultAddNotificationChannels(builder, notificationChannels)

def EnforcementDefaultStartNotificationChannelsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartNotificationChannelsVector(builder, numElems: int) -> int:
    return EnforcementDefaultStartNotificationChannelsVector(builder, numElems)

def EnforcementDefaultAddIsActive(builder: flatbuffers.Builder, isActive: bool):
    builder.PrependBoolSlot(8, isActive, 0)

def AddIsActive(builder: flatbuffers.Builder, isActive: bool):
    EnforcementDefaultAddIsActive(builder, isActive)

def EnforcementDefaultEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return EnforcementDefaultEnd(builder)
