# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from flatbuffers.table import Table
from revturbine.bundle.RuleTarget import RuleTarget
from typing import Optional
np = import_numpy()

class EntitlementRule(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EntitlementRule()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEntitlementRule(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EntitlementRuleBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # EntitlementRule
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EntitlementRule
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EntitlementRule
    def EntitlementIdx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EntitlementRule
    def PlanIdxs(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # EntitlementRule
    def PlanIdxsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # EntitlementRule
    def PlanIdxsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EntitlementRule
    def PlanIdxsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # EntitlementRule
    def SegmentIdxs(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # EntitlementRule
    def SegmentIdxsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # EntitlementRule
    def SegmentIdxsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EntitlementRule
    def SegmentIdxsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # EntitlementRule
    def TypeFieldsType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EntitlementRule
    def TypeFields(self) -> Optional[flatbuffers.table.Table]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # EntitlementRule
    def Allocation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EntitlementRule
    def Targets(self, j: int) -> Optional[RuleTarget]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = RuleTarget()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EntitlementRule
    def TargetsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EntitlementRule
    def TargetsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

def EntitlementRuleStart(builder: flatbuffers.Builder):
    builder.StartObject(8)

def Start(builder: flatbuffers.Builder):
    EntitlementRuleStart(builder)

def EntitlementRuleAddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUint32Slot(0, sourceId, 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    EntitlementRuleAddSourceId(builder, sourceId)

def EntitlementRuleAddEntitlementIdx(builder: flatbuffers.Builder, entitlementIdx: int):
    builder.PrependUint32Slot(1, entitlementIdx, 0)

def AddEntitlementIdx(builder: flatbuffers.Builder, entitlementIdx: int):
    EntitlementRuleAddEntitlementIdx(builder, entitlementIdx)

def EntitlementRuleAddPlanIdxs(builder: flatbuffers.Builder, planIdxs: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(planIdxs), 0)

def AddPlanIdxs(builder: flatbuffers.Builder, planIdxs: int):
    EntitlementRuleAddPlanIdxs(builder, planIdxs)

def EntitlementRuleStartPlanIdxsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPlanIdxsVector(builder, numElems: int) -> int:
    return EntitlementRuleStartPlanIdxsVector(builder, numElems)

def EntitlementRuleAddSegmentIdxs(builder: flatbuffers.Builder, segmentIdxs: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(segmentIdxs), 0)

def AddSegmentIdxs(builder: flatbuffers.Builder, segmentIdxs: int):
    EntitlementRuleAddSegmentIdxs(builder, segmentIdxs)

def EntitlementRuleStartSegmentIdxsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSegmentIdxsVector(builder, numElems: int) -> int:
    return EntitlementRuleStartSegmentIdxsVector(builder, numElems)

def EntitlementRuleAddTypeFieldsType(builder: flatbuffers.Builder, typeFieldsType: int):
    builder.PrependUint8Slot(4, typeFieldsType, 0)

def AddTypeFieldsType(builder: flatbuffers.Builder, typeFieldsType: int):
    EntitlementRuleAddTypeFieldsType(builder, typeFieldsType)

def EntitlementRuleAddTypeFields(builder: flatbuffers.Builder, typeFields: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(typeFields), 0)

def AddTypeFields(builder: flatbuffers.Builder, typeFields: int):
    EntitlementRuleAddTypeFields(builder, typeFields)

def EntitlementRuleAddAllocation(builder: flatbuffers.Builder, allocation: int):
    builder.PrependUint8Slot(6, allocation, 0)

def AddAllocation(builder: flatbuffers.Builder, allocation: int):
    EntitlementRuleAddAllocation(builder, allocation)

def EntitlementRuleAddTargets(builder: flatbuffers.Builder, targets: int):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(targets), 0)

def AddTargets(builder: flatbuffers.Builder, targets: int):
    EntitlementRuleAddTargets(builder, targets)

def EntitlementRuleStartTargetsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartTargetsVector(builder, numElems: int) -> int:
    return EntitlementRuleStartTargetsVector(builder, numElems)

def EntitlementRuleEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return EntitlementRuleEnd(builder)
