# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

class EntitlementType(object):
    unknown = 0
    feature = 1
    usage_limit = 2
    credits = 3
    seats = 4
    tiered = 5
