from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.EntitlementType import EntitlementType

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Entitlement(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Entitlement: ...
  @classmethod
  def GetRootAsEntitlement(cls, buf: bytes, offset: int) -> Entitlement: ...
  @classmethod
  def EntitlementBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceId(self) -> int: ...
  def UniqueHandle(self) -> int: ...
  def Name(self) -> int: ...
  def Type(self) -> typing.Literal[EntitlementType.unknown, EntitlementType.feature, EntitlementType.usage_limit, EntitlementType.credits, EntitlementType.seats, EntitlementType.tiered]: ...
  def Unit(self) -> int: ...
  def TierHandles(self, i: int) -> typing.List[int]: ...
  def TierHandlesAsNumpy(self) -> np.ndarray: ...
  def TierHandlesLength(self) -> int: ...
  def TierHandlesIsNone(self) -> bool: ...
def EntitlementStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def EntitlementAddSourceId(builder: flatbuffers.Builder, sourceId: int) -> None: ...
def EntitlementAddUniqueHandle(builder: flatbuffers.Builder, uniqueHandle: int) -> None: ...
def EntitlementAddName(builder: flatbuffers.Builder, name: int) -> None: ...
def EntitlementAddType(builder: flatbuffers.Builder, type: typing.Literal[EntitlementType.unknown, EntitlementType.feature, EntitlementType.usage_limit, EntitlementType.credits, EntitlementType.seats, EntitlementType.tiered]) -> None: ...
def EntitlementAddUnit(builder: flatbuffers.Builder, unit: int) -> None: ...
def EntitlementAddTierHandles(builder: flatbuffers.Builder, tierHandles: uoffset) -> None: ...
def EntitlementStartTierHandlesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTierHandlesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def EntitlementEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

