# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Entitlement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Entitlement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEntitlement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EntitlementBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # Entitlement
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Entitlement
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Entitlement
    def UniqueHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Entitlement
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Entitlement
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Entitlement
    def Unit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Entitlement
    def TierHandles(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Entitlement
    def TierHandlesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Entitlement
    def TierHandlesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Entitlement
    def TierHandlesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def EntitlementStart(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    EntitlementStart(builder)

def EntitlementAddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUint32Slot(0, sourceId, 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    EntitlementAddSourceId(builder, sourceId)

def EntitlementAddUniqueHandle(builder: flatbuffers.Builder, uniqueHandle: int):
    builder.PrependUint32Slot(1, uniqueHandle, 0)

def AddUniqueHandle(builder: flatbuffers.Builder, uniqueHandle: int):
    EntitlementAddUniqueHandle(builder, uniqueHandle)

def EntitlementAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUint32Slot(2, name, 0)

def AddName(builder: flatbuffers.Builder, name: int):
    EntitlementAddName(builder, name)

def EntitlementAddType(builder: flatbuffers.Builder, type: int):
    builder.PrependUint8Slot(3, type, 0)

def AddType(builder: flatbuffers.Builder, type: int):
    EntitlementAddType(builder, type)

def EntitlementAddUnit(builder: flatbuffers.Builder, unit: int):
    builder.PrependUint32Slot(4, unit, 0)

def AddUnit(builder: flatbuffers.Builder, unit: int):
    EntitlementAddUnit(builder, unit)

def EntitlementAddTierHandles(builder: flatbuffers.Builder, tierHandles: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(tierHandles), 0)

def AddTierHandles(builder: flatbuffers.Builder, tierHandles: int):
    EntitlementAddTierHandles(builder, tierHandles)

def EntitlementStartTierHandlesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartTierHandlesVector(builder, numElems: int) -> int:
    return EntitlementStartTierHandlesVector(builder, numElems)

def EntitlementEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return EntitlementEnd(builder)
