from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from flatbuffers import table
from revturbine.bundle.RuleTarget import RuleTarget
from revturbine.bundle.TypeFields import TypeFields
from revturbine.bundle.UsageAllocation import UsageAllocation

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class EntitlementRule(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> EntitlementRule: ...
  @classmethod
  def GetRootAsEntitlementRule(cls, buf: bytes, offset: int) -> EntitlementRule: ...
  @classmethod
  def EntitlementRuleBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceId(self) -> int: ...
  def EntitlementIdx(self) -> int: ...
  def PlanIdxs(self, i: int) -> typing.List[int]: ...
  def PlanIdxsAsNumpy(self) -> np.ndarray: ...
  def PlanIdxsLength(self) -> int: ...
  def PlanIdxsIsNone(self) -> bool: ...
  def SegmentIdxs(self, i: int) -> typing.List[int]: ...
  def SegmentIdxsAsNumpy(self) -> np.ndarray: ...
  def SegmentIdxsLength(self) -> int: ...
  def SegmentIdxsIsNone(self) -> bool: ...
  def TypeFieldsType(self) -> typing.Literal[TypeFields.NONE, TypeFields.FeatureFields, TypeFields.UsageLimitFields, TypeFields.CreditsFields, TypeFields.SeatsFields, TypeFields.TieredFields]: ...
  def TypeFields(self) -> table.Table | None: ...
  def Allocation(self) -> typing.Literal[UsageAllocation.unknown, UsageAllocation.account_pool, UsageAllocation.per_instance, UsageAllocation.per_user, UsageAllocation.per_user_pooled]: ...
  def Targets(self, i: int) -> RuleTarget | None: ...
  def TargetsLength(self) -> int: ...
  def TargetsIsNone(self) -> bool: ...
def EntitlementRuleStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def EntitlementRuleAddSourceId(builder: flatbuffers.Builder, sourceId: int) -> None: ...
def EntitlementRuleAddEntitlementIdx(builder: flatbuffers.Builder, entitlementIdx: int) -> None: ...
def EntitlementRuleAddPlanIdxs(builder: flatbuffers.Builder, planIdxs: uoffset) -> None: ...
def EntitlementRuleStartPlanIdxsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartPlanIdxsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def EntitlementRuleAddSegmentIdxs(builder: flatbuffers.Builder, segmentIdxs: uoffset) -> None: ...
def EntitlementRuleStartSegmentIdxsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSegmentIdxsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def EntitlementRuleAddTypeFieldsType(builder: flatbuffers.Builder, typeFieldsType: typing.Literal[TypeFields.NONE, TypeFields.FeatureFields, TypeFields.UsageLimitFields, TypeFields.CreditsFields, TypeFields.SeatsFields, TypeFields.TieredFields]) -> None: ...
def EntitlementRuleAddTypeFields(builder: flatbuffers.Builder, typeFields: uoffset) -> None: ...
def EntitlementRuleAddAllocation(builder: flatbuffers.Builder, allocation: typing.Literal[UsageAllocation.unknown, UsageAllocation.account_pool, UsageAllocation.per_instance, UsageAllocation.per_user, UsageAllocation.per_user_pooled]) -> None: ...
def EntitlementRuleAddTargets(builder: flatbuffers.Builder, targets: uoffset) -> None: ...
def EntitlementRuleStartTargetsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTargetsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def EntitlementRuleEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

