# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class ExtensionRule(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExtensionRule()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExtensionRule(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ExtensionRuleBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # ExtensionRule
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExtensionRule
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExtensionRule
    def SchemaVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExtensionRule
    def Config(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ExtensionRule
    def ConfigAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ExtensionRule
    def ConfigLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExtensionRule
    def ConfigIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def ExtensionRuleStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    ExtensionRuleStart(builder)

def ExtensionRuleAddKind(builder: flatbuffers.Builder, kind: int):
    builder.PrependUint32Slot(0, kind, 0)

def AddKind(builder: flatbuffers.Builder, kind: int):
    ExtensionRuleAddKind(builder, kind)

def ExtensionRuleAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: int):
    builder.PrependUint32Slot(1, schemaVersion, 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: int):
    ExtensionRuleAddSchemaVersion(builder, schemaVersion)

def ExtensionRuleAddConfig(builder: flatbuffers.Builder, config: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(config), 0)

def AddConfig(builder: flatbuffers.Builder, config: int):
    ExtensionRuleAddConfig(builder, config)

def ExtensionRuleStartConfigVector(builder, numElems: int) -> int:
    return builder.StartVector(1, numElems, 1)

def StartConfigVector(builder, numElems: int) -> int:
    return ExtensionRuleStartConfigVector(builder, numElems)

def ExtensionRuleEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ExtensionRuleEnd(builder)
