from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ExtensionRule(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ExtensionRule: ...
  @classmethod
  def GetRootAsExtensionRule(cls, buf: bytes, offset: int) -> ExtensionRule: ...
  @classmethod
  def ExtensionRuleBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Kind(self) -> int: ...
  def SchemaVersion(self) -> int: ...
  def Config(self, i: int) -> typing.List[int]: ...
  def ConfigAsNumpy(self) -> np.ndarray: ...
  def ConfigLength(self) -> int: ...
  def ConfigIsNone(self) -> bool: ...
def ExtensionRuleStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ExtensionRuleAddKind(builder: flatbuffers.Builder, kind: int) -> None: ...
def ExtensionRuleAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: int) -> None: ...
def ExtensionRuleAddConfig(builder: flatbuffers.Builder, config: uoffset) -> None: ...
def ExtensionRuleStartConfigVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartConfigVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ExtensionRuleEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

