from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class FeatureFields(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FeatureFields: ...
  @classmethod
  def GetRootAsFeatureFields(cls, buf: bytes, offset: int) -> FeatureFields: ...
  @classmethod
  def FeatureFieldsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Enabled(self) -> bool: ...
def FeatureFieldsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def FeatureFieldsAddEnabled(builder: flatbuffers.Builder, enabled: bool) -> None: ...
def FeatureFieldsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

