# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class FreeTrialRule(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FreeTrialRule()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFreeTrialRule(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FreeTrialRuleBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # FreeTrialRule
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FreeTrialRule
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FreeTrialRule
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FreeTrialRule
    def PlanId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FreeTrialRule
    def UsageEntitlementHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FreeTrialRule
    def UsageLimitValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def FreeTrialRuleStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    FreeTrialRuleStart(builder)

def FreeTrialRuleAddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUint32Slot(0, sourceId, 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    FreeTrialRuleAddSourceId(builder, sourceId)

def FreeTrialRuleAddHandle(builder: flatbuffers.Builder, handle: int):
    builder.PrependUint32Slot(1, handle, 0)

def AddHandle(builder: flatbuffers.Builder, handle: int):
    FreeTrialRuleAddHandle(builder, handle)

def FreeTrialRuleAddPlanId(builder: flatbuffers.Builder, planId: int):
    builder.PrependUint32Slot(2, planId, 0)

def AddPlanId(builder: flatbuffers.Builder, planId: int):
    FreeTrialRuleAddPlanId(builder, planId)

def FreeTrialRuleAddUsageEntitlementHandle(builder: flatbuffers.Builder, usageEntitlementHandle: int):
    builder.PrependUint32Slot(3, usageEntitlementHandle, 0)

def AddUsageEntitlementHandle(builder: flatbuffers.Builder, usageEntitlementHandle: int):
    FreeTrialRuleAddUsageEntitlementHandle(builder, usageEntitlementHandle)

def FreeTrialRuleAddUsageLimitValue(builder: flatbuffers.Builder, usageLimitValue: int):
    builder.PrependInt64Slot(4, usageLimitValue, 0)

def AddUsageLimitValue(builder: flatbuffers.Builder, usageLimitValue: int):
    FreeTrialRuleAddUsageLimitValue(builder, usageLimitValue)

def FreeTrialRuleEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return FreeTrialRuleEnd(builder)
