from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class FreeTrialRule(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FreeTrialRule: ...
  @classmethod
  def GetRootAsFreeTrialRule(cls, buf: bytes, offset: int) -> FreeTrialRule: ...
  @classmethod
  def FreeTrialRuleBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceId(self) -> int: ...
  def Handle(self) -> int: ...
  def PlanId(self) -> int: ...
  def UsageEntitlementHandle(self) -> int: ...
  def UsageLimitValue(self) -> int: ...
def FreeTrialRuleStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def FreeTrialRuleAddSourceId(builder: flatbuffers.Builder, sourceId: int) -> None: ...
def FreeTrialRuleAddHandle(builder: flatbuffers.Builder, handle: int) -> None: ...
def FreeTrialRuleAddPlanId(builder: flatbuffers.Builder, planId: int) -> None: ...
def FreeTrialRuleAddUsageEntitlementHandle(builder: flatbuffers.Builder, usageEntitlementHandle: int) -> None: ...
def FreeTrialRuleAddUsageLimitValue(builder: flatbuffers.Builder, usageLimitValue: int) -> None: ...
def FreeTrialRuleEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

