from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Header(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Header: ...
  @classmethod
  def GetRootAsHeader(cls, buf: bytes, offset: int) -> Header: ...
  @classmethod
  def HeaderBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Magic(self) -> str | None: ...
  def SchemaVersion(self) -> int: ...
  def RuntimeAbi(self) -> int: ...
  def ConfigVersion(self) -> str | None: ...
  def ExportedAtMs(self) -> int: ...
  def BuiltAtMs(self) -> int: ...
  def SourceSha256(self) -> str | None: ...
  def TenantId(self) -> str | None: ...
  def ChangeSetId(self) -> str | None: ...
  def PackageSchemaVersion(self) -> str | None: ...
  def EnvironmentId(self) -> str | None: ...
  def PlaybookHandle(self) -> str | None: ...
def HeaderStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def HeaderAddMagic(builder: flatbuffers.Builder, magic: uoffset) -> None: ...
def HeaderAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: int) -> None: ...
def HeaderAddRuntimeAbi(builder: flatbuffers.Builder, runtimeAbi: int) -> None: ...
def HeaderAddConfigVersion(builder: flatbuffers.Builder, configVersion: uoffset) -> None: ...
def HeaderAddExportedAtMs(builder: flatbuffers.Builder, exportedAtMs: int) -> None: ...
def HeaderAddBuiltAtMs(builder: flatbuffers.Builder, builtAtMs: int) -> None: ...
def HeaderAddSourceSha256(builder: flatbuffers.Builder, sourceSha256: uoffset) -> None: ...
def HeaderAddTenantId(builder: flatbuffers.Builder, tenantId: uoffset) -> None: ...
def HeaderAddChangeSetId(builder: flatbuffers.Builder, changeSetId: uoffset) -> None: ...
def HeaderAddPackageSchemaVersion(builder: flatbuffers.Builder, packageSchemaVersion: uoffset) -> None: ...
def HeaderAddEnvironmentId(builder: flatbuffers.Builder, environmentId: uoffset) -> None: ...
def HeaderAddPlaybookHandle(builder: flatbuffers.Builder, playbookHandle: uoffset) -> None: ...
def HeaderEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

