# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Header(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Header()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHeader(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def HeaderBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # Header
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Header
    def Magic(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def SchemaVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Header
    def RuntimeAbi(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Header
    def ConfigVersion(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def ExportedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Header
    def BuiltAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Header
    def SourceSha256(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def TenantId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def ChangeSetId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def PackageSchemaVersion(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def EnvironmentId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Header
    def PlaybookHandle(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def HeaderStart(builder: flatbuffers.Builder):
    builder.StartObject(12)

def Start(builder: flatbuffers.Builder):
    HeaderStart(builder)

def HeaderAddMagic(builder: flatbuffers.Builder, magic: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(magic), 0)

def AddMagic(builder: flatbuffers.Builder, magic: int):
    HeaderAddMagic(builder, magic)

def HeaderAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: int):
    builder.PrependUint32Slot(1, schemaVersion, 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: int):
    HeaderAddSchemaVersion(builder, schemaVersion)

def HeaderAddRuntimeAbi(builder: flatbuffers.Builder, runtimeAbi: int):
    builder.PrependUint32Slot(2, runtimeAbi, 0)

def AddRuntimeAbi(builder: flatbuffers.Builder, runtimeAbi: int):
    HeaderAddRuntimeAbi(builder, runtimeAbi)

def HeaderAddConfigVersion(builder: flatbuffers.Builder, configVersion: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(configVersion), 0)

def AddConfigVersion(builder: flatbuffers.Builder, configVersion: int):
    HeaderAddConfigVersion(builder, configVersion)

def HeaderAddExportedAtMs(builder: flatbuffers.Builder, exportedAtMs: int):
    builder.PrependInt64Slot(4, exportedAtMs, 0)

def AddExportedAtMs(builder: flatbuffers.Builder, exportedAtMs: int):
    HeaderAddExportedAtMs(builder, exportedAtMs)

def HeaderAddBuiltAtMs(builder: flatbuffers.Builder, builtAtMs: int):
    builder.PrependInt64Slot(5, builtAtMs, 0)

def AddBuiltAtMs(builder: flatbuffers.Builder, builtAtMs: int):
    HeaderAddBuiltAtMs(builder, builtAtMs)

def HeaderAddSourceSha256(builder: flatbuffers.Builder, sourceSha256: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(sourceSha256), 0)

def AddSourceSha256(builder: flatbuffers.Builder, sourceSha256: int):
    HeaderAddSourceSha256(builder, sourceSha256)

def HeaderAddTenantId(builder: flatbuffers.Builder, tenantId: int):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(tenantId), 0)

def AddTenantId(builder: flatbuffers.Builder, tenantId: int):
    HeaderAddTenantId(builder, tenantId)

def HeaderAddChangeSetId(builder: flatbuffers.Builder, changeSetId: int):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(changeSetId), 0)

def AddChangeSetId(builder: flatbuffers.Builder, changeSetId: int):
    HeaderAddChangeSetId(builder, changeSetId)

def HeaderAddPackageSchemaVersion(builder: flatbuffers.Builder, packageSchemaVersion: int):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(packageSchemaVersion), 0)

def AddPackageSchemaVersion(builder: flatbuffers.Builder, packageSchemaVersion: int):
    HeaderAddPackageSchemaVersion(builder, packageSchemaVersion)

def HeaderAddEnvironmentId(builder: flatbuffers.Builder, environmentId: int):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(environmentId), 0)

def AddEnvironmentId(builder: flatbuffers.Builder, environmentId: int):
    HeaderAddEnvironmentId(builder, environmentId)

def HeaderAddPlaybookHandle(builder: flatbuffers.Builder, playbookHandle: int):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(playbookHandle), 0)

def AddPlaybookHandle(builder: flatbuffers.Builder, playbookHandle: int):
    HeaderAddPlaybookHandle(builder, playbookHandle)

def HeaderEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return HeaderEnd(builder)
