# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from revturbine.bundle.MessageBlockChild import MessageBlockChild
from revturbine.bundle.MessageBlockContent import MessageBlockContent
from revturbine.bundle.MessageBlockSegmentOverride import MessageBlockSegmentOverride
from typing import Optional
np = import_numpy()

class MessageBlock(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MessageBlock()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMessageBlock(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MessageBlockBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # MessageBlock
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MessageBlock
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MessageBlock
    def TenantId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MessageBlock
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MessageBlock
    def SurfaceTemplateIdx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MessageBlock
    def DefaultContent(self) -> Optional[MessageBlockContent]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = MessageBlockContent()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MessageBlock
    def SegmentOverrides(self, j: int) -> Optional[MessageBlockSegmentOverride]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = MessageBlockSegmentOverride()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MessageBlock
    def SegmentOverridesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MessageBlock
    def SegmentOverridesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # MessageBlock
    def ChildBlocks(self, j: int) -> Optional[MessageBlockChild]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = MessageBlockChild()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MessageBlock
    def ChildBlocksLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MessageBlock
    def ChildBlocksIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # MessageBlock
    def TokensUsed(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MessageBlock
    def TokensUsedAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # MessageBlock
    def TokensUsedLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MessageBlock
    def TokensUsedIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # MessageBlock
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # MessageBlock
    def CreatedAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MessageBlock
    def UpdatedAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def MessageBlockStart(builder: flatbuffers.Builder):
    builder.StartObject(11)

def Start(builder: flatbuffers.Builder):
    MessageBlockStart(builder)

def MessageBlockAddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUint32Slot(0, sourceId, 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    MessageBlockAddSourceId(builder, sourceId)

def MessageBlockAddTenantId(builder: flatbuffers.Builder, tenantId: int):
    builder.PrependUint32Slot(1, tenantId, 0)

def AddTenantId(builder: flatbuffers.Builder, tenantId: int):
    MessageBlockAddTenantId(builder, tenantId)

def MessageBlockAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUint32Slot(2, name, 0)

def AddName(builder: flatbuffers.Builder, name: int):
    MessageBlockAddName(builder, name)

def MessageBlockAddSurfaceTemplateIdx(builder: flatbuffers.Builder, surfaceTemplateIdx: int):
    builder.PrependUint32Slot(3, surfaceTemplateIdx, 0)

def AddSurfaceTemplateIdx(builder: flatbuffers.Builder, surfaceTemplateIdx: int):
    MessageBlockAddSurfaceTemplateIdx(builder, surfaceTemplateIdx)

def MessageBlockAddDefaultContent(builder: flatbuffers.Builder, defaultContent: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(defaultContent), 0)

def AddDefaultContent(builder: flatbuffers.Builder, defaultContent: int):
    MessageBlockAddDefaultContent(builder, defaultContent)

def MessageBlockAddSegmentOverrides(builder: flatbuffers.Builder, segmentOverrides: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(segmentOverrides), 0)

def AddSegmentOverrides(builder: flatbuffers.Builder, segmentOverrides: int):
    MessageBlockAddSegmentOverrides(builder, segmentOverrides)

def MessageBlockStartSegmentOverridesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSegmentOverridesVector(builder, numElems: int) -> int:
    return MessageBlockStartSegmentOverridesVector(builder, numElems)

def MessageBlockAddChildBlocks(builder: flatbuffers.Builder, childBlocks: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(childBlocks), 0)

def AddChildBlocks(builder: flatbuffers.Builder, childBlocks: int):
    MessageBlockAddChildBlocks(builder, childBlocks)

def MessageBlockStartChildBlocksVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartChildBlocksVector(builder, numElems: int) -> int:
    return MessageBlockStartChildBlocksVector(builder, numElems)

def MessageBlockAddTokensUsed(builder: flatbuffers.Builder, tokensUsed: int):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(tokensUsed), 0)

def AddTokensUsed(builder: flatbuffers.Builder, tokensUsed: int):
    MessageBlockAddTokensUsed(builder, tokensUsed)

def MessageBlockStartTokensUsedVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartTokensUsedVector(builder, numElems: int) -> int:
    return MessageBlockStartTokensUsedVector(builder, numElems)

def MessageBlockAddStatus(builder: flatbuffers.Builder, status: int):
    builder.PrependUint8Slot(8, status, 0)

def AddStatus(builder: flatbuffers.Builder, status: int):
    MessageBlockAddStatus(builder, status)

def MessageBlockAddCreatedAt(builder: flatbuffers.Builder, createdAt: int):
    builder.PrependUint32Slot(9, createdAt, 0)

def AddCreatedAt(builder: flatbuffers.Builder, createdAt: int):
    MessageBlockAddCreatedAt(builder, createdAt)

def MessageBlockAddUpdatedAt(builder: flatbuffers.Builder, updatedAt: int):
    builder.PrependUint32Slot(10, updatedAt, 0)

def AddUpdatedAt(builder: flatbuffers.Builder, updatedAt: int):
    MessageBlockAddUpdatedAt(builder, updatedAt)

def MessageBlockEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MessageBlockEnd(builder)
