from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.MessageBlockChild import MessageBlockChild
from revturbine.bundle.MessageBlockContent import MessageBlockContent
from revturbine.bundle.MessageBlockSegmentOverride import MessageBlockSegmentOverride
from revturbine.bundle.MessageBlockStatus import MessageBlockStatus

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MessageBlock(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MessageBlock: ...
  @classmethod
  def GetRootAsMessageBlock(cls, buf: bytes, offset: int) -> MessageBlock: ...
  @classmethod
  def MessageBlockBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceId(self) -> int: ...
  def TenantId(self) -> int: ...
  def Name(self) -> int: ...
  def SurfaceTemplateIdx(self) -> int: ...
  def DefaultContent(self) -> MessageBlockContent | None: ...
  def SegmentOverrides(self, i: int) -> MessageBlockSegmentOverride | None: ...
  def SegmentOverridesLength(self) -> int: ...
  def SegmentOverridesIsNone(self) -> bool: ...
  def ChildBlocks(self, i: int) -> MessageBlockChild | None: ...
  def ChildBlocksLength(self) -> int: ...
  def ChildBlocksIsNone(self) -> bool: ...
  def TokensUsed(self, i: int) -> typing.List[int]: ...
  def TokensUsedAsNumpy(self) -> np.ndarray: ...
  def TokensUsedLength(self) -> int: ...
  def TokensUsedIsNone(self) -> bool: ...
  def Status(self) -> typing.Literal[MessageBlockStatus.unknown, MessageBlockStatus.draft, MessageBlockStatus.active, MessageBlockStatus.archived]: ...
  def CreatedAt(self) -> int: ...
  def UpdatedAt(self) -> int: ...
def MessageBlockStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MessageBlockAddSourceId(builder: flatbuffers.Builder, sourceId: int) -> None: ...
def MessageBlockAddTenantId(builder: flatbuffers.Builder, tenantId: int) -> None: ...
def MessageBlockAddName(builder: flatbuffers.Builder, name: int) -> None: ...
def MessageBlockAddSurfaceTemplateIdx(builder: flatbuffers.Builder, surfaceTemplateIdx: int) -> None: ...
def MessageBlockAddDefaultContent(builder: flatbuffers.Builder, defaultContent: uoffset) -> None: ...
def MessageBlockAddSegmentOverrides(builder: flatbuffers.Builder, segmentOverrides: uoffset) -> None: ...
def MessageBlockStartSegmentOverridesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSegmentOverridesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def MessageBlockAddChildBlocks(builder: flatbuffers.Builder, childBlocks: uoffset) -> None: ...
def MessageBlockStartChildBlocksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartChildBlocksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def MessageBlockAddTokensUsed(builder: flatbuffers.Builder, tokensUsed: uoffset) -> None: ...
def MessageBlockStartTokensUsedVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTokensUsedVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def MessageBlockAddStatus(builder: flatbuffers.Builder, status: typing.Literal[MessageBlockStatus.unknown, MessageBlockStatus.draft, MessageBlockStatus.active, MessageBlockStatus.archived]) -> None: ...
def MessageBlockAddCreatedAt(builder: flatbuffers.Builder, createdAt: int) -> None: ...
def MessageBlockAddUpdatedAt(builder: flatbuffers.Builder, updatedAt: int) -> None: ...
def MessageBlockEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

