# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from revturbine.bundle.MessageBlockField import MessageBlockField
from typing import Optional
np = import_numpy()

class MessageBlockContent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MessageBlockContent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMessageBlockContent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MessageBlockContentBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # MessageBlockContent
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MessageBlockContent
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MessageBlockContent
    def Body(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MessageBlockContent
    def CtaLabel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MessageBlockContent
    def SecondaryCtaLabel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MessageBlockContent
    def Extra(self, j: int) -> Optional[MessageBlockField]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            obj = MessageBlockField()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MessageBlockContent
    def ExtraLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MessageBlockContent
    def ExtraIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def MessageBlockContentStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    MessageBlockContentStart(builder)

def MessageBlockContentAddHeader(builder: flatbuffers.Builder, header: int):
    builder.PrependUint32Slot(0, header, 0)

def AddHeader(builder: flatbuffers.Builder, header: int):
    MessageBlockContentAddHeader(builder, header)

def MessageBlockContentAddBody(builder: flatbuffers.Builder, body: int):
    builder.PrependUint32Slot(1, body, 0)

def AddBody(builder: flatbuffers.Builder, body: int):
    MessageBlockContentAddBody(builder, body)

def MessageBlockContentAddCtaLabel(builder: flatbuffers.Builder, ctaLabel: int):
    builder.PrependUint32Slot(2, ctaLabel, 0)

def AddCtaLabel(builder: flatbuffers.Builder, ctaLabel: int):
    MessageBlockContentAddCtaLabel(builder, ctaLabel)

def MessageBlockContentAddSecondaryCtaLabel(builder: flatbuffers.Builder, secondaryCtaLabel: int):
    builder.PrependUint32Slot(3, secondaryCtaLabel, 0)

def AddSecondaryCtaLabel(builder: flatbuffers.Builder, secondaryCtaLabel: int):
    MessageBlockContentAddSecondaryCtaLabel(builder, secondaryCtaLabel)

def MessageBlockContentAddExtra(builder: flatbuffers.Builder, extra: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(extra), 0)

def AddExtra(builder: flatbuffers.Builder, extra: int):
    MessageBlockContentAddExtra(builder, extra)

def MessageBlockContentStartExtraVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 4)

def StartExtraVector(builder, numElems: int) -> int:
    return MessageBlockContentStartExtraVector(builder, numElems)

def MessageBlockContentEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MessageBlockContentEnd(builder)
