# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from revturbine.bundle.MessageBlockContent import MessageBlockContent
from typing import Optional
np = import_numpy()

class MessageBlockSegmentOverride(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MessageBlockSegmentOverride()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMessageBlockSegmentOverride(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MessageBlockSegmentOverrideBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # MessageBlockSegmentOverride
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MessageBlockSegmentOverride
    def SegmentValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MessageBlockSegmentOverride
    def Content(self) -> Optional[MessageBlockContent]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = MessageBlockContent()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def MessageBlockSegmentOverrideStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    MessageBlockSegmentOverrideStart(builder)

def MessageBlockSegmentOverrideAddSegmentValue(builder: flatbuffers.Builder, segmentValue: int):
    builder.PrependUint32Slot(0, segmentValue, 0)

def AddSegmentValue(builder: flatbuffers.Builder, segmentValue: int):
    MessageBlockSegmentOverrideAddSegmentValue(builder, segmentValue)

def MessageBlockSegmentOverrideAddContent(builder: flatbuffers.Builder, content: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(content), 0)

def AddContent(builder: flatbuffers.Builder, content: int):
    MessageBlockSegmentOverrideAddContent(builder, content)

def MessageBlockSegmentOverrideEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MessageBlockSegmentOverrideEnd(builder)
