from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.MessageBlockField import MessageBlockField

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MessageBlockContent(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MessageBlockContent: ...
  @classmethod
  def GetRootAsMessageBlockContent(cls, buf: bytes, offset: int) -> MessageBlockContent: ...
  @classmethod
  def MessageBlockContentBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Header(self) -> int: ...
  def Body(self) -> int: ...
  def CtaLabel(self) -> int: ...
  def SecondaryCtaLabel(self) -> int: ...
  def Extra(self, i: int) -> MessageBlockField | None: ...
  def ExtraLength(self) -> int: ...
  def ExtraIsNone(self) -> bool: ...
def MessageBlockContentStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MessageBlockContentAddHeader(builder: flatbuffers.Builder, header: int) -> None: ...
def MessageBlockContentAddBody(builder: flatbuffers.Builder, body: int) -> None: ...
def MessageBlockContentAddCtaLabel(builder: flatbuffers.Builder, ctaLabel: int) -> None: ...
def MessageBlockContentAddSecondaryCtaLabel(builder: flatbuffers.Builder, secondaryCtaLabel: int) -> None: ...
def MessageBlockContentAddExtra(builder: flatbuffers.Builder, extra: uoffset) -> None: ...
def MessageBlockContentStartExtraVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartExtraVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def MessageBlockContentEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

