from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.MessageBlockContent import MessageBlockContent

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MessageBlockSegmentOverride(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MessageBlockSegmentOverride: ...
  @classmethod
  def GetRootAsMessageBlockSegmentOverride(cls, buf: bytes, offset: int) -> MessageBlockSegmentOverride: ...
  @classmethod
  def MessageBlockSegmentOverrideBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SegmentValue(self) -> int: ...
  def Content(self) -> MessageBlockContent | None: ...
def MessageBlockSegmentOverrideStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MessageBlockSegmentOverrideAddSegmentValue(builder: flatbuffers.Builder, segmentValue: int) -> None: ...
def MessageBlockSegmentOverrideAddContent(builder: flatbuffers.Builder, content: uoffset) -> None: ...
def MessageBlockSegmentOverrideEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

