# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class MessageBlockChild(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MessageBlockChild()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMessageBlockChild(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MessageBlockChildBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # MessageBlockChild
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MessageBlockChild
    def Slot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MessageBlockChild
    def BlockIdx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MessageBlockChild
    def BlockSourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def MessageBlockChildStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    MessageBlockChildStart(builder)

def MessageBlockChildAddSlot(builder: flatbuffers.Builder, slot: int):
    builder.PrependUint32Slot(0, slot, 0)

def AddSlot(builder: flatbuffers.Builder, slot: int):
    MessageBlockChildAddSlot(builder, slot)

def MessageBlockChildAddBlockIdx(builder: flatbuffers.Builder, blockIdx: int):
    builder.PrependUint32Slot(1, blockIdx, 0)

def AddBlockIdx(builder: flatbuffers.Builder, blockIdx: int):
    MessageBlockChildAddBlockIdx(builder, blockIdx)

def MessageBlockChildAddBlockSourceId(builder: flatbuffers.Builder, blockSourceId: int):
    builder.PrependUint32Slot(2, blockSourceId, 0)

def AddBlockSourceId(builder: flatbuffers.Builder, blockSourceId: int):
    MessageBlockChildAddBlockSourceId(builder, blockSourceId)

def MessageBlockChildEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MessageBlockChildEnd(builder)
