from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MessageBlockChild(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MessageBlockChild: ...
  @classmethod
  def GetRootAsMessageBlockChild(cls, buf: bytes, offset: int) -> MessageBlockChild: ...
  @classmethod
  def MessageBlockChildBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Slot(self) -> int: ...
  def BlockIdx(self) -> int: ...
  def BlockSourceId(self) -> int: ...
def MessageBlockChildStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MessageBlockChildAddSlot(builder: flatbuffers.Builder, slot: int) -> None: ...
def MessageBlockChildAddBlockIdx(builder: flatbuffers.Builder, blockIdx: int) -> None: ...
def MessageBlockChildAddBlockSourceId(builder: flatbuffers.Builder, blockSourceId: int) -> None: ...
def MessageBlockChildEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

