from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MeterBinding(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MeterBinding: ...
  @classmethod
  def GetRootAsMeterBinding(cls, buf: bytes, offset: int) -> MeterBinding: ...
  @classmethod
  def MeterBindingBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Handle(self) -> int: ...
  def EntitlementHandle(self) -> int: ...
  def MeterHandle(self) -> int: ...
  def Limit(self) -> int: ...
  def ResetPeriod(self) -> int: ...
def MeterBindingStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MeterBindingAddHandle(builder: flatbuffers.Builder, handle: int) -> None: ...
def MeterBindingAddEntitlementHandle(builder: flatbuffers.Builder, entitlementHandle: int) -> None: ...
def MeterBindingAddMeterHandle(builder: flatbuffers.Builder, meterHandle: int) -> None: ...
def MeterBindingAddLimit(builder: flatbuffers.Builder, limit: int) -> None: ...
def MeterBindingAddResetPeriod(builder: flatbuffers.Builder, resetPeriod: int) -> None: ...
def MeterBindingEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

