# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class MeterBinding(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MeterBinding()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMeterBinding(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MeterBindingBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # MeterBinding
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MeterBinding
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MeterBinding
    def EntitlementHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MeterBinding
    def MeterHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MeterBinding
    def Limit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # MeterBinding
    def ResetPeriod(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def MeterBindingStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    MeterBindingStart(builder)

def MeterBindingAddHandle(builder: flatbuffers.Builder, handle: int):
    builder.PrependUint32Slot(0, handle, 0)

def AddHandle(builder: flatbuffers.Builder, handle: int):
    MeterBindingAddHandle(builder, handle)

def MeterBindingAddEntitlementHandle(builder: flatbuffers.Builder, entitlementHandle: int):
    builder.PrependUint32Slot(1, entitlementHandle, 0)

def AddEntitlementHandle(builder: flatbuffers.Builder, entitlementHandle: int):
    MeterBindingAddEntitlementHandle(builder, entitlementHandle)

def MeterBindingAddMeterHandle(builder: flatbuffers.Builder, meterHandle: int):
    builder.PrependUint32Slot(2, meterHandle, 0)

def AddMeterHandle(builder: flatbuffers.Builder, meterHandle: int):
    MeterBindingAddMeterHandle(builder, meterHandle)

def MeterBindingAddLimit(builder: flatbuffers.Builder, limit: int):
    builder.PrependInt64Slot(3, limit, 0)

def AddLimit(builder: flatbuffers.Builder, limit: int):
    MeterBindingAddLimit(builder, limit)

def MeterBindingAddResetPeriod(builder: flatbuffers.Builder, resetPeriod: int):
    builder.PrependUint32Slot(4, resetPeriod, 0)

def AddResetPeriod(builder: flatbuffers.Builder, resetPeriod: int):
    MeterBindingAddResetPeriod(builder, resetPeriod)

def MeterBindingEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MeterBindingEnd(builder)
