# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from revturbine.bundle.CtaConfig import CtaConfig
from revturbine.bundle.SurfaceFieldEntry import SurfaceFieldEntry
from typing import Optional
np = import_numpy()

class PayloadSurface(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PayloadSurface()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPayloadSurface(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PayloadSurfaceBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # PayloadSurface
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PayloadSurface
    def TemplateIdx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PayloadSurface
    def TemplateSourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PayloadSurface
    def Fields(self, j: int) -> Optional[SurfaceFieldEntry]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            obj = SurfaceFieldEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PayloadSurface
    def FieldsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PayloadSurface
    def FieldsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # PayloadSurface
    def Ctas(self, j: int) -> Optional[CtaConfig]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = CtaConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PayloadSurface
    def CtasLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PayloadSurface
    def CtasIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def PayloadSurfaceStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    PayloadSurfaceStart(builder)

def PayloadSurfaceAddTemplateIdx(builder: flatbuffers.Builder, templateIdx: int):
    builder.PrependUint32Slot(0, templateIdx, 0)

def AddTemplateIdx(builder: flatbuffers.Builder, templateIdx: int):
    PayloadSurfaceAddTemplateIdx(builder, templateIdx)

def PayloadSurfaceAddTemplateSourceId(builder: flatbuffers.Builder, templateSourceId: int):
    builder.PrependUint32Slot(1, templateSourceId, 0)

def AddTemplateSourceId(builder: flatbuffers.Builder, templateSourceId: int):
    PayloadSurfaceAddTemplateSourceId(builder, templateSourceId)

def PayloadSurfaceAddFields(builder: flatbuffers.Builder, fields: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(fields), 0)

def AddFields(builder: flatbuffers.Builder, fields: int):
    PayloadSurfaceAddFields(builder, fields)

def PayloadSurfaceStartFieldsVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 4)

def StartFieldsVector(builder, numElems: int) -> int:
    return PayloadSurfaceStartFieldsVector(builder, numElems)

def PayloadSurfaceAddCtas(builder: flatbuffers.Builder, ctas: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(ctas), 0)

def AddCtas(builder: flatbuffers.Builder, ctas: int):
    PayloadSurfaceAddCtas(builder, ctas)

def PayloadSurfaceStartCtasVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartCtasVector(builder, numElems: int) -> int:
    return PayloadSurfaceStartCtasVector(builder, numElems)

def PayloadSurfaceEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PayloadSurfaceEnd(builder)
