from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.CtaConfig import CtaConfig
from revturbine.bundle.SurfaceFieldEntry import SurfaceFieldEntry

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class PayloadSurface(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> PayloadSurface: ...
  @classmethod
  def GetRootAsPayloadSurface(cls, buf: bytes, offset: int) -> PayloadSurface: ...
  @classmethod
  def PayloadSurfaceBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TemplateIdx(self) -> int: ...
  def TemplateSourceId(self) -> int: ...
  def Fields(self, i: int) -> SurfaceFieldEntry | None: ...
  def FieldsLength(self) -> int: ...
  def FieldsIsNone(self) -> bool: ...
  def Ctas(self, i: int) -> CtaConfig | None: ...
  def CtasLength(self) -> int: ...
  def CtasIsNone(self) -> bool: ...
def PayloadSurfaceStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def PayloadSurfaceAddTemplateIdx(builder: flatbuffers.Builder, templateIdx: int) -> None: ...
def PayloadSurfaceAddTemplateSourceId(builder: flatbuffers.Builder, templateSourceId: int) -> None: ...
def PayloadSurfaceAddFields(builder: flatbuffers.Builder, fields: uoffset) -> None: ...
def PayloadSurfaceStartFieldsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartFieldsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PayloadSurfaceAddCtas(builder: flatbuffers.Builder, ctas: uoffset) -> None: ...
def PayloadSurfaceStartCtasVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartCtasVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PayloadSurfaceEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

