from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.SegmentChip import SegmentChip

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class PayloadTarget(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> PayloadTarget: ...
  @classmethod
  def GetRootAsPayloadTarget(cls, buf: bytes, offset: int) -> PayloadTarget: ...
  @classmethod
  def PayloadTargetBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PlanIdxs(self, i: int) -> typing.List[int]: ...
  def PlanIdxsAsNumpy(self) -> np.ndarray: ...
  def PlanIdxsLength(self) -> int: ...
  def PlanIdxsIsNone(self) -> bool: ...
  def SegmentChips(self, i: int) -> SegmentChip | None: ...
  def SegmentChipsLength(self) -> int: ...
  def SegmentChipsIsNone(self) -> bool: ...
  def BillingCadences(self, i: int) -> typing.List[int]: ...
  def BillingCadencesAsNumpy(self) -> np.ndarray: ...
  def BillingCadencesLength(self) -> int: ...
  def BillingCadencesIsNone(self) -> bool: ...
def PayloadTargetStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def PayloadTargetAddPlanIdxs(builder: flatbuffers.Builder, planIdxs: uoffset) -> None: ...
def PayloadTargetStartPlanIdxsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartPlanIdxsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PayloadTargetAddSegmentChips(builder: flatbuffers.Builder, segmentChips: uoffset) -> None: ...
def PayloadTargetStartSegmentChipsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSegmentChipsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PayloadTargetAddBillingCadences(builder: flatbuffers.Builder, billingCadences: uoffset) -> None: ...
def PayloadTargetStartBillingCadencesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartBillingCadencesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PayloadTargetEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

