# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from revturbine.bundle.SegmentChip import SegmentChip
from typing import Optional
np = import_numpy()

class PayloadTarget(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PayloadTarget()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPayloadTarget(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PayloadTargetBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # PayloadTarget
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PayloadTarget
    def PlanIdxs(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # PayloadTarget
    def PlanIdxsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # PayloadTarget
    def PlanIdxsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PayloadTarget
    def PlanIdxsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # PayloadTarget
    def SegmentChips(self, j: int) -> Optional[SegmentChip]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            obj = SegmentChip()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PayloadTarget
    def SegmentChipsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PayloadTarget
    def SegmentChipsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # PayloadTarget
    def BillingCadences(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # PayloadTarget
    def BillingCadencesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # PayloadTarget
    def BillingCadencesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PayloadTarget
    def BillingCadencesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def PayloadTargetStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    PayloadTargetStart(builder)

def PayloadTargetAddPlanIdxs(builder: flatbuffers.Builder, planIdxs: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(planIdxs), 0)

def AddPlanIdxs(builder: flatbuffers.Builder, planIdxs: int):
    PayloadTargetAddPlanIdxs(builder, planIdxs)

def PayloadTargetStartPlanIdxsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPlanIdxsVector(builder, numElems: int) -> int:
    return PayloadTargetStartPlanIdxsVector(builder, numElems)

def PayloadTargetAddSegmentChips(builder: flatbuffers.Builder, segmentChips: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(segmentChips), 0)

def AddSegmentChips(builder: flatbuffers.Builder, segmentChips: int):
    PayloadTargetAddSegmentChips(builder, segmentChips)

def PayloadTargetStartSegmentChipsVector(builder, numElems: int) -> int:
    return builder.StartVector(16, numElems, 4)

def StartSegmentChipsVector(builder, numElems: int) -> int:
    return PayloadTargetStartSegmentChipsVector(builder, numElems)

def PayloadTargetAddBillingCadences(builder: flatbuffers.Builder, billingCadences: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(billingCadences), 0)

def AddBillingCadences(builder: flatbuffers.Builder, billingCadences: int):
    PayloadTargetAddBillingCadences(builder, billingCadences)

def PayloadTargetStartBillingCadencesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartBillingCadencesVector(builder, numElems: int) -> int:
    return PayloadTargetStartBillingCadencesVector(builder, numElems)

def PayloadTargetEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PayloadTargetEnd(builder)
