# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class PayloadCaps(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 12

    # PayloadCaps
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PayloadCaps
    def HasMaxPerPeriod(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # PayloadCaps
    def MaxPerPeriod(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))
    # PayloadCaps
    def MaxPerPeriodCount(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # PayloadCaps
    def CooldownDays(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreatePayloadCaps(builder, hasMaxPerPeriod, maxPerPeriod, maxPerPeriodCount, cooldownDays):
    builder.Prep(4, 12)
    builder.PrependInt32(cooldownDays)
    builder.PrependUint32(maxPerPeriodCount)
    builder.Pad(2)
    builder.PrependUint8(maxPerPeriod)
    builder.PrependBool(hasMaxPerPeriod)
    return builder.Offset()
