from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.CapPeriod import CapPeriod

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class PayloadCaps(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def HasMaxPerPeriod(self) -> bool: ...
  def MaxPerPeriod(self) -> typing.Literal[CapPeriod.unknown, CapPeriod.session, CapPeriod.day, CapPeriod.week, CapPeriod.month, CapPeriod.lifetime]: ...
  def MaxPerPeriodCount(self) -> int: ...
  def CooldownDays(self) -> int: ...

def CreatePayloadCaps(builder: flatbuffers.Builder, hasMaxPerPeriod: bool, maxPerPeriod: typing.Literal[CapPeriod.unknown, CapPeriod.session, CapPeriod.day, CapPeriod.week, CapPeriod.month, CapPeriod.lifetime], maxPerPeriodCount: int, cooldownDays: int) -> uoffset: ...

