# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from revturbine.bundle.TokenValueEntry import TokenValueEntry
from typing import Optional
np = import_numpy()

class PersonalizationToken(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PersonalizationToken()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPersonalizationToken(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PersonalizationTokenBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # PersonalizationToken
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PersonalizationToken
    def Token(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PersonalizationToken
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PersonalizationToken
    def Description(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PersonalizationToken
    def Category(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PersonalizationToken
    def DataSource(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PersonalizationToken
    def ExampleValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PersonalizationToken
    def ValueMap(self, j: int) -> Optional[TokenValueEntry]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            obj = TokenValueEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PersonalizationToken
    def ValueMapLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PersonalizationToken
    def ValueMapIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # PersonalizationToken
    def Format(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def PersonalizationTokenStart(builder: flatbuffers.Builder):
    builder.StartObject(8)

def Start(builder: flatbuffers.Builder):
    PersonalizationTokenStart(builder)

def PersonalizationTokenAddToken(builder: flatbuffers.Builder, token: int):
    builder.PrependUint32Slot(0, token, 0)

def AddToken(builder: flatbuffers.Builder, token: int):
    PersonalizationTokenAddToken(builder, token)

def PersonalizationTokenAddLabel(builder: flatbuffers.Builder, label: int):
    builder.PrependUint32Slot(1, label, 0)

def AddLabel(builder: flatbuffers.Builder, label: int):
    PersonalizationTokenAddLabel(builder, label)

def PersonalizationTokenAddDescription(builder: flatbuffers.Builder, description: int):
    builder.PrependUint32Slot(2, description, 0)

def AddDescription(builder: flatbuffers.Builder, description: int):
    PersonalizationTokenAddDescription(builder, description)

def PersonalizationTokenAddCategory(builder: flatbuffers.Builder, category: int):
    builder.PrependUint8Slot(3, category, 0)

def AddCategory(builder: flatbuffers.Builder, category: int):
    PersonalizationTokenAddCategory(builder, category)

def PersonalizationTokenAddDataSource(builder: flatbuffers.Builder, dataSource: int):
    builder.PrependUint32Slot(4, dataSource, 0)

def AddDataSource(builder: flatbuffers.Builder, dataSource: int):
    PersonalizationTokenAddDataSource(builder, dataSource)

def PersonalizationTokenAddExampleValue(builder: flatbuffers.Builder, exampleValue: int):
    builder.PrependUint32Slot(5, exampleValue, 0)

def AddExampleValue(builder: flatbuffers.Builder, exampleValue: int):
    PersonalizationTokenAddExampleValue(builder, exampleValue)

def PersonalizationTokenAddValueMap(builder: flatbuffers.Builder, valueMap: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(valueMap), 0)

def AddValueMap(builder: flatbuffers.Builder, valueMap: int):
    PersonalizationTokenAddValueMap(builder, valueMap)

def PersonalizationTokenStartValueMapVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 4)

def StartValueMapVector(builder, numElems: int) -> int:
    return PersonalizationTokenStartValueMapVector(builder, numElems)

def PersonalizationTokenAddFormat(builder: flatbuffers.Builder, format: int):
    builder.PrependUint8Slot(7, format, 0)

def AddFormat(builder: flatbuffers.Builder, format: int):
    PersonalizationTokenAddFormat(builder, format)

def PersonalizationTokenEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PersonalizationTokenEnd(builder)
