from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.TokenCategory import TokenCategory
from revturbine.bundle.TokenFormat import TokenFormat
from revturbine.bundle.TokenValueEntry import TokenValueEntry

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class PersonalizationToken(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> PersonalizationToken: ...
  @classmethod
  def GetRootAsPersonalizationToken(cls, buf: bytes, offset: int) -> PersonalizationToken: ...
  @classmethod
  def PersonalizationTokenBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Token(self) -> int: ...
  def Label(self) -> int: ...
  def Description(self) -> int: ...
  def Category(self) -> typing.Literal[TokenCategory.unknown, TokenCategory.user, TokenCategory.plan, TokenCategory.usage, TokenCategory.trial, TokenCategory.billing, TokenCategory.promotion, TokenCategory.custom]: ...
  def DataSource(self) -> int: ...
  def ExampleValue(self) -> int: ...
  def ValueMap(self, i: int) -> TokenValueEntry | None: ...
  def ValueMapLength(self) -> int: ...
  def ValueMapIsNone(self) -> bool: ...
  def Format(self) -> typing.Literal[TokenFormat.unknown, TokenFormat.string_, TokenFormat.number, TokenFormat.currency, TokenFormat.percentage, TokenFormat.date]: ...
def PersonalizationTokenStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def PersonalizationTokenAddToken(builder: flatbuffers.Builder, token: int) -> None: ...
def PersonalizationTokenAddLabel(builder: flatbuffers.Builder, label: int) -> None: ...
def PersonalizationTokenAddDescription(builder: flatbuffers.Builder, description: int) -> None: ...
def PersonalizationTokenAddCategory(builder: flatbuffers.Builder, category: typing.Literal[TokenCategory.unknown, TokenCategory.user, TokenCategory.plan, TokenCategory.usage, TokenCategory.trial, TokenCategory.billing, TokenCategory.promotion, TokenCategory.custom]) -> None: ...
def PersonalizationTokenAddDataSource(builder: flatbuffers.Builder, dataSource: int) -> None: ...
def PersonalizationTokenAddExampleValue(builder: flatbuffers.Builder, exampleValue: int) -> None: ...
def PersonalizationTokenAddValueMap(builder: flatbuffers.Builder, valueMap: uoffset) -> None: ...
def PersonalizationTokenStartValueMapVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartValueMapVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PersonalizationTokenAddFormat(builder: flatbuffers.Builder, format: typing.Literal[TokenFormat.unknown, TokenFormat.string_, TokenFormat.number, TokenFormat.currency, TokenFormat.percentage, TokenFormat.date]) -> None: ...
def PersonalizationTokenEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

