# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class PlacementTrigger(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 32

    # PlacementTrigger
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlacementTrigger
    def Type(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # PlacementTrigger
    def TrialType(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))
    # PlacementTrigger
    def SlotIdx(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # PlacementTrigger
    def EntitlementIdx(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # PlacementTrigger
    def TierThreshold(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # PlacementTrigger
    def Qualifier(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # PlacementTrigger
    def ThresholdPercent(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))
    # PlacementTrigger
    def ProgressPercent(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))
    # PlacementTrigger
    def DaysBeforeEnd(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(28))

def CreatePlacementTrigger(builder, type, trialType, slotIdx, entitlementIdx, tierThreshold, qualifier, thresholdPercent, progressPercent, daysBeforeEnd):
    builder.Prep(4, 32)
    builder.PrependInt32(daysBeforeEnd)
    builder.PrependFloat32(progressPercent)
    builder.PrependFloat32(thresholdPercent)
    builder.PrependUint32(qualifier)
    builder.PrependUint32(tierThreshold)
    builder.PrependUint32(entitlementIdx)
    builder.PrependUint32(slotIdx)
    builder.Pad(2)
    builder.PrependUint8(trialType)
    builder.PrependUint8(type)
    return builder.Offset()
