from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.ContentLink import ContentLink
from revturbine.bundle.PayloadCaps import PayloadCaps
from revturbine.bundle.PayloadSourceMode import PayloadSourceMode
from revturbine.bundle.PayloadSurface import PayloadSurface
from revturbine.bundle.PayloadTarget import PayloadTarget

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class PlacementPayload(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> PlacementPayload: ...
  @classmethod
  def GetRootAsPlacementPayload(cls, buf: bytes, offset: int) -> PlacementPayload: ...
  @classmethod
  def PlacementPayloadBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceId(self) -> int: ...
  def PlacementIdx(self) -> int: ...
  def PlacementSourceId(self) -> int: ...
  def Target(self) -> PayloadTarget | None: ...
  def Caps(self) -> PayloadCaps | None: ...
  def CreatedAt(self) -> int: ...
  def UpdatedAt(self) -> int: ...
  def SourceMode(self) -> typing.Literal[PayloadSourceMode.inline, PayloadSourceMode.content_linked]: ...
  def Surfaces(self, i: int) -> PayloadSurface | None: ...
  def SurfacesLength(self) -> int: ...
  def SurfacesIsNone(self) -> bool: ...
  def ContentLink(self) -> ContentLink | None: ...
  def SurfaceSlotIds(self, i: int) -> typing.List[int]: ...
  def SurfaceSlotIdsAsNumpy(self) -> np.ndarray: ...
  def SurfaceSlotIdsLength(self) -> int: ...
  def SurfaceSlotIdsIsNone(self) -> bool: ...
def PlacementPayloadStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def PlacementPayloadAddSourceId(builder: flatbuffers.Builder, sourceId: int) -> None: ...
def PlacementPayloadAddPlacementIdx(builder: flatbuffers.Builder, placementIdx: int) -> None: ...
def PlacementPayloadAddPlacementSourceId(builder: flatbuffers.Builder, placementSourceId: int) -> None: ...
def PlacementPayloadAddTarget(builder: flatbuffers.Builder, target: uoffset) -> None: ...
def PlacementPayloadAddCaps(builder: flatbuffers.Builder, caps: uoffset) -> None: ...
def PlacementPayloadAddCreatedAt(builder: flatbuffers.Builder, createdAt: int) -> None: ...
def PlacementPayloadAddUpdatedAt(builder: flatbuffers.Builder, updatedAt: int) -> None: ...
def PlacementPayloadAddSourceMode(builder: flatbuffers.Builder, sourceMode: typing.Literal[PayloadSourceMode.inline, PayloadSourceMode.content_linked]) -> None: ...
def PlacementPayloadAddSurfaces(builder: flatbuffers.Builder, surfaces: uoffset) -> None: ...
def PlacementPayloadStartSurfacesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSurfacesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PlacementPayloadAddContentLink(builder: flatbuffers.Builder, contentLink: uoffset) -> None: ...
def PlacementPayloadAddSurfaceSlotIds(builder: flatbuffers.Builder, surfaceSlotIds: uoffset) -> None: ...
def PlacementPayloadStartSurfaceSlotIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSurfaceSlotIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PlacementPayloadEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

