# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

class PlacementCategory(object):
    unknown = 0
    fixed = 1
    gated = 2
    usage_credit_seat = 3
    trials = 4
    other_conversion = 5
    retention = 6
