# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class PlacementSlot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlacementSlot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlacementSlot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PlacementSlotBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # PlacementSlot
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlacementSlot
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PlacementSlot
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PlacementSlot
    def Description(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PlacementSlot
    def SurfaceType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PlacementSlot
    def PlacementHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PlacementSlot
    def Template(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def PlacementSlotStart(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    PlacementSlotStart(builder)

def PlacementSlotAddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUint32Slot(0, sourceId, 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    PlacementSlotAddSourceId(builder, sourceId)

def PlacementSlotAddLabel(builder: flatbuffers.Builder, label: int):
    builder.PrependUint32Slot(1, label, 0)

def AddLabel(builder: flatbuffers.Builder, label: int):
    PlacementSlotAddLabel(builder, label)

def PlacementSlotAddDescription(builder: flatbuffers.Builder, description: int):
    builder.PrependUint32Slot(2, description, 0)

def AddDescription(builder: flatbuffers.Builder, description: int):
    PlacementSlotAddDescription(builder, description)

def PlacementSlotAddSurfaceType(builder: flatbuffers.Builder, surfaceType: int):
    builder.PrependUint32Slot(3, surfaceType, 0)

def AddSurfaceType(builder: flatbuffers.Builder, surfaceType: int):
    PlacementSlotAddSurfaceType(builder, surfaceType)

def PlacementSlotAddPlacementHandle(builder: flatbuffers.Builder, placementHandle: int):
    builder.PrependUint32Slot(4, placementHandle, 0)

def AddPlacementHandle(builder: flatbuffers.Builder, placementHandle: int):
    PlacementSlotAddPlacementHandle(builder, placementHandle)

def PlacementSlotAddTemplate(builder: flatbuffers.Builder, template: int):
    builder.PrependUint32Slot(5, template, 0)

def AddTemplate(builder: flatbuffers.Builder, template: int):
    PlacementSlotAddTemplate(builder, template)

def PlacementSlotEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PlacementSlotEnd(builder)
