from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class PlacementSetting(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> PlacementSetting: ...
  @classmethod
  def GetRootAsPlacementSetting(cls, buf: bytes, offset: int) -> PlacementSetting: ...
  @classmethod
  def PlacementSettingBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Handle(self) -> int: ...
  def GlobalFrequencyCap(self) -> int: ...
  def GlobalFrequencyCapPeriod(self) -> int: ...
  def SuppressForPaid(self) -> bool: ...
  def SuppressForTrial(self) -> bool: ...
  def DefaultDismissCooldownHours(self) -> int: ...
  def AllowStacking(self) -> bool: ...
  def PriorityCollisionStrategy(self) -> int: ...
def PlacementSettingStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def PlacementSettingAddHandle(builder: flatbuffers.Builder, handle: int) -> None: ...
def PlacementSettingAddGlobalFrequencyCap(builder: flatbuffers.Builder, globalFrequencyCap: int) -> None: ...
def PlacementSettingAddGlobalFrequencyCapPeriod(builder: flatbuffers.Builder, globalFrequencyCapPeriod: int) -> None: ...
def PlacementSettingAddSuppressForPaid(builder: flatbuffers.Builder, suppressForPaid: bool) -> None: ...
def PlacementSettingAddSuppressForTrial(builder: flatbuffers.Builder, suppressForTrial: bool) -> None: ...
def PlacementSettingAddDefaultDismissCooldownHours(builder: flatbuffers.Builder, defaultDismissCooldownHours: int) -> None: ...
def PlacementSettingAddAllowStacking(builder: flatbuffers.Builder, allowStacking: bool) -> None: ...
def PlacementSettingAddPriorityCollisionStrategy(builder: flatbuffers.Builder, priorityCollisionStrategy: int) -> None: ...
def PlacementSettingEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

