from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class PlacementSlot(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> PlacementSlot: ...
  @classmethod
  def GetRootAsPlacementSlot(cls, buf: bytes, offset: int) -> PlacementSlot: ...
  @classmethod
  def PlacementSlotBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceId(self) -> int: ...
  def Label(self) -> int: ...
  def Description(self) -> int: ...
  def SurfaceType(self) -> int: ...
  def PlacementHandle(self) -> int: ...
  def Template(self) -> int: ...
def PlacementSlotStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def PlacementSlotAddSourceId(builder: flatbuffers.Builder, sourceId: int) -> None: ...
def PlacementSlotAddLabel(builder: flatbuffers.Builder, label: int) -> None: ...
def PlacementSlotAddDescription(builder: flatbuffers.Builder, description: int) -> None: ...
def PlacementSlotAddSurfaceType(builder: flatbuffers.Builder, surfaceType: int) -> None: ...
def PlacementSlotAddPlacementHandle(builder: flatbuffers.Builder, placementHandle: int) -> None: ...
def PlacementSlotAddTemplate(builder: flatbuffers.Builder, template: int) -> None: ...
def PlacementSlotEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

