from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.TrialType import TrialType
from revturbine.bundle.TriggerType import TriggerType

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class PlacementTrigger(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def Type(self) -> typing.Literal[TriggerType.unknown, TriggerType.surface_render, TriggerType.entitlement_gate, TriggerType.usage_threshold, TriggerType.credit_threshold, TriggerType.seat_threshold, TriggerType.trial_started, TriggerType.trial_progress, TriggerType.trial_ending, TriggerType.trial_ended, TriggerType.trial_converted, TriggerType.qualifier]: ...
  def TrialType(self) -> typing.Literal[TrialType.none, TrialType.free, TrialType.reverse]: ...
  def SlotIdx(self) -> int: ...
  def EntitlementIdx(self) -> int: ...
  def TierThreshold(self) -> int: ...
  def Qualifier(self) -> int: ...
  def ThresholdPercent(self) -> float: ...
  def ProgressPercent(self) -> float: ...
  def DaysBeforeEnd(self) -> int: ...

def CreatePlacementTrigger(builder: flatbuffers.Builder, type: typing.Literal[TriggerType.unknown, TriggerType.surface_render, TriggerType.entitlement_gate, TriggerType.usage_threshold, TriggerType.credit_threshold, TriggerType.seat_threshold, TriggerType.trial_started, TriggerType.trial_progress, TriggerType.trial_ending, TriggerType.trial_ended, TriggerType.trial_converted, TriggerType.qualifier], trialType: typing.Literal[TrialType.none, TrialType.free, TrialType.reverse], slotIdx: int, entitlementIdx: int, tierThreshold: int, qualifier: int, thresholdPercent: float, progressPercent: float, daysBeforeEnd: int) -> uoffset: ...

