# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from revturbine.bundle.PlacementTrigger import PlacementTrigger
from revturbine.bundle.StudioPayload import StudioPayload
from typing import Optional
np = import_numpy()

class Placement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Placement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlacement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PlacementBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # Placement
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Placement
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Placement
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Placement
    def Category(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Placement
    def Trigger(self) -> Optional[PlacementTrigger]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = PlacementTrigger()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Placement
    def Payloads(self, j: int) -> Optional[StudioPayload]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = StudioPayload()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Placement
    def PayloadsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Placement
    def PayloadsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Placement
    def Order(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def PlacementStart(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    PlacementStart(builder)

def PlacementAddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUint32Slot(0, sourceId, 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    PlacementAddSourceId(builder, sourceId)

def PlacementAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUint32Slot(1, name, 0)

def AddName(builder: flatbuffers.Builder, name: int):
    PlacementAddName(builder, name)

def PlacementAddCategory(builder: flatbuffers.Builder, category: int):
    builder.PrependUint8Slot(2, category, 0)

def AddCategory(builder: flatbuffers.Builder, category: int):
    PlacementAddCategory(builder, category)

def PlacementAddTrigger(builder: flatbuffers.Builder, trigger: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(trigger), 0)

def AddTrigger(builder: flatbuffers.Builder, trigger: Any):
    PlacementAddTrigger(builder, trigger)

def PlacementAddPayloads(builder: flatbuffers.Builder, payloads: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(payloads), 0)

def AddPayloads(builder: flatbuffers.Builder, payloads: int):
    PlacementAddPayloads(builder, payloads)

def PlacementStartPayloadsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPayloadsVector(builder, numElems: int) -> int:
    return PlacementStartPayloadsVector(builder, numElems)

def PlacementAddOrder(builder: flatbuffers.Builder, order: int):
    builder.PrependUint32Slot(5, order, 0)

def AddOrder(builder: flatbuffers.Builder, order: int):
    PlacementAddOrder(builder, order)

def PlacementEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PlacementEnd(builder)
