# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from revturbine.bundle.ContentLink import ContentLink
from revturbine.bundle.PayloadCaps import PayloadCaps
from revturbine.bundle.PayloadSurface import PayloadSurface
from revturbine.bundle.PayloadTarget import PayloadTarget
from typing import Optional
np = import_numpy()

class PlacementPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlacementPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlacementPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PlacementPayloadBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # PlacementPayload
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlacementPayload
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PlacementPayload
    def PlacementIdx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PlacementPayload
    def PlacementSourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PlacementPayload
    def Target(self) -> Optional[PayloadTarget]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = PayloadTarget()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PlacementPayload
    def Caps(self) -> Optional[PayloadCaps]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = PayloadCaps()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PlacementPayload
    def CreatedAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PlacementPayload
    def UpdatedAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PlacementPayload
    def SourceMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PlacementPayload
    def Surfaces(self, j: int) -> Optional[PayloadSurface]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = PayloadSurface()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PlacementPayload
    def SurfacesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PlacementPayload
    def SurfacesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # PlacementPayload
    def ContentLink(self) -> Optional[ContentLink]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = o + self._tab.Pos
            obj = ContentLink()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PlacementPayload
    def SurfaceSlotIds(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # PlacementPayload
    def SurfaceSlotIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # PlacementPayload
    def SurfaceSlotIdsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PlacementPayload
    def SurfaceSlotIdsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

def PlacementPayloadStart(builder: flatbuffers.Builder):
    builder.StartObject(11)

def Start(builder: flatbuffers.Builder):
    PlacementPayloadStart(builder)

def PlacementPayloadAddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUint32Slot(0, sourceId, 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    PlacementPayloadAddSourceId(builder, sourceId)

def PlacementPayloadAddPlacementIdx(builder: flatbuffers.Builder, placementIdx: int):
    builder.PrependUint32Slot(1, placementIdx, 0)

def AddPlacementIdx(builder: flatbuffers.Builder, placementIdx: int):
    PlacementPayloadAddPlacementIdx(builder, placementIdx)

def PlacementPayloadAddPlacementSourceId(builder: flatbuffers.Builder, placementSourceId: int):
    builder.PrependUint32Slot(2, placementSourceId, 0)

def AddPlacementSourceId(builder: flatbuffers.Builder, placementSourceId: int):
    PlacementPayloadAddPlacementSourceId(builder, placementSourceId)

def PlacementPayloadAddTarget(builder: flatbuffers.Builder, target: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(target), 0)

def AddTarget(builder: flatbuffers.Builder, target: int):
    PlacementPayloadAddTarget(builder, target)

def PlacementPayloadAddCaps(builder: flatbuffers.Builder, caps: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(caps), 0)

def AddCaps(builder: flatbuffers.Builder, caps: Any):
    PlacementPayloadAddCaps(builder, caps)

def PlacementPayloadAddCreatedAt(builder: flatbuffers.Builder, createdAt: int):
    builder.PrependUint32Slot(5, createdAt, 0)

def AddCreatedAt(builder: flatbuffers.Builder, createdAt: int):
    PlacementPayloadAddCreatedAt(builder, createdAt)

def PlacementPayloadAddUpdatedAt(builder: flatbuffers.Builder, updatedAt: int):
    builder.PrependUint32Slot(6, updatedAt, 0)

def AddUpdatedAt(builder: flatbuffers.Builder, updatedAt: int):
    PlacementPayloadAddUpdatedAt(builder, updatedAt)

def PlacementPayloadAddSourceMode(builder: flatbuffers.Builder, sourceMode: int):
    builder.PrependUint8Slot(7, sourceMode, 0)

def AddSourceMode(builder: flatbuffers.Builder, sourceMode: int):
    PlacementPayloadAddSourceMode(builder, sourceMode)

def PlacementPayloadAddSurfaces(builder: flatbuffers.Builder, surfaces: int):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(surfaces), 0)

def AddSurfaces(builder: flatbuffers.Builder, surfaces: int):
    PlacementPayloadAddSurfaces(builder, surfaces)

def PlacementPayloadStartSurfacesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSurfacesVector(builder, numElems: int) -> int:
    return PlacementPayloadStartSurfacesVector(builder, numElems)

def PlacementPayloadAddContentLink(builder: flatbuffers.Builder, contentLink: Any):
    builder.PrependStructSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(contentLink), 0)

def AddContentLink(builder: flatbuffers.Builder, contentLink: Any):
    PlacementPayloadAddContentLink(builder, contentLink)

def PlacementPayloadAddSurfaceSlotIds(builder: flatbuffers.Builder, surfaceSlotIds: int):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(surfaceSlotIds), 0)

def AddSurfaceSlotIds(builder: flatbuffers.Builder, surfaceSlotIds: int):
    PlacementPayloadAddSurfaceSlotIds(builder, surfaceSlotIds)

def PlacementPayloadStartSurfaceSlotIdsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSurfaceSlotIdsVector(builder, numElems: int) -> int:
    return PlacementPayloadStartSurfaceSlotIdsVector(builder, numElems)

def PlacementPayloadEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PlacementPayloadEnd(builder)
