from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.PlacementCategory import PlacementCategory
from revturbine.bundle.PlacementTrigger import PlacementTrigger
from revturbine.bundle.StudioPayload import StudioPayload

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Placement(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Placement: ...
  @classmethod
  def GetRootAsPlacement(cls, buf: bytes, offset: int) -> Placement: ...
  @classmethod
  def PlacementBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceId(self) -> int: ...
  def Name(self) -> int: ...
  def Category(self) -> typing.Literal[PlacementCategory.unknown, PlacementCategory.fixed, PlacementCategory.gated, PlacementCategory.usage_credit_seat, PlacementCategory.trials, PlacementCategory.other_conversion, PlacementCategory.retention]: ...
  def Trigger(self) -> PlacementTrigger | None: ...
  def Payloads(self, i: int) -> StudioPayload | None: ...
  def PayloadsLength(self) -> int: ...
  def PayloadsIsNone(self) -> bool: ...
  def Order(self) -> int: ...
def PlacementStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def PlacementAddSourceId(builder: flatbuffers.Builder, sourceId: int) -> None: ...
def PlacementAddName(builder: flatbuffers.Builder, name: int) -> None: ...
def PlacementAddCategory(builder: flatbuffers.Builder, category: typing.Literal[PlacementCategory.unknown, PlacementCategory.fixed, PlacementCategory.gated, PlacementCategory.usage_credit_seat, PlacementCategory.trials, PlacementCategory.other_conversion, PlacementCategory.retention]) -> None: ...
def PlacementAddTrigger(builder: flatbuffers.Builder, trigger: uoffset) -> None: ...
def PlacementAddPayloads(builder: flatbuffers.Builder, payloads: uoffset) -> None: ...
def PlacementStartPayloadsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartPayloadsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PlacementAddOrder(builder: flatbuffers.Builder, order: int) -> None: ...
def PlacementEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

