# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class PlacementSetting(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlacementSetting()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlacementSetting(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PlacementSettingBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # PlacementSetting
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlacementSetting
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PlacementSetting
    def GlobalFrequencyCap(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PlacementSetting
    def GlobalFrequencyCapPeriod(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PlacementSetting
    def SuppressForPaid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # PlacementSetting
    def SuppressForTrial(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # PlacementSetting
    def DefaultDismissCooldownHours(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PlacementSetting
    def AllowStacking(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # PlacementSetting
    def PriorityCollisionStrategy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def PlacementSettingStart(builder: flatbuffers.Builder):
    builder.StartObject(8)

def Start(builder: flatbuffers.Builder):
    PlacementSettingStart(builder)

def PlacementSettingAddHandle(builder: flatbuffers.Builder, handle: int):
    builder.PrependUint32Slot(0, handle, 0)

def AddHandle(builder: flatbuffers.Builder, handle: int):
    PlacementSettingAddHandle(builder, handle)

def PlacementSettingAddGlobalFrequencyCap(builder: flatbuffers.Builder, globalFrequencyCap: int):
    builder.PrependUint32Slot(1, globalFrequencyCap, 0)

def AddGlobalFrequencyCap(builder: flatbuffers.Builder, globalFrequencyCap: int):
    PlacementSettingAddGlobalFrequencyCap(builder, globalFrequencyCap)

def PlacementSettingAddGlobalFrequencyCapPeriod(builder: flatbuffers.Builder, globalFrequencyCapPeriod: int):
    builder.PrependUint32Slot(2, globalFrequencyCapPeriod, 0)

def AddGlobalFrequencyCapPeriod(builder: flatbuffers.Builder, globalFrequencyCapPeriod: int):
    PlacementSettingAddGlobalFrequencyCapPeriod(builder, globalFrequencyCapPeriod)

def PlacementSettingAddSuppressForPaid(builder: flatbuffers.Builder, suppressForPaid: bool):
    builder.PrependBoolSlot(3, suppressForPaid, 0)

def AddSuppressForPaid(builder: flatbuffers.Builder, suppressForPaid: bool):
    PlacementSettingAddSuppressForPaid(builder, suppressForPaid)

def PlacementSettingAddSuppressForTrial(builder: flatbuffers.Builder, suppressForTrial: bool):
    builder.PrependBoolSlot(4, suppressForTrial, 0)

def AddSuppressForTrial(builder: flatbuffers.Builder, suppressForTrial: bool):
    PlacementSettingAddSuppressForTrial(builder, suppressForTrial)

def PlacementSettingAddDefaultDismissCooldownHours(builder: flatbuffers.Builder, defaultDismissCooldownHours: int):
    builder.PrependInt64Slot(5, defaultDismissCooldownHours, 0)

def AddDefaultDismissCooldownHours(builder: flatbuffers.Builder, defaultDismissCooldownHours: int):
    PlacementSettingAddDefaultDismissCooldownHours(builder, defaultDismissCooldownHours)

def PlacementSettingAddAllowStacking(builder: flatbuffers.Builder, allowStacking: bool):
    builder.PrependBoolSlot(6, allowStacking, 0)

def AddAllowStacking(builder: flatbuffers.Builder, allowStacking: bool):
    PlacementSettingAddAllowStacking(builder, allowStacking)

def PlacementSettingAddPriorityCollisionStrategy(builder: flatbuffers.Builder, priorityCollisionStrategy: int):
    builder.PrependUint32Slot(7, priorityCollisionStrategy, 0)

def AddPriorityCollisionStrategy(builder: flatbuffers.Builder, priorityCollisionStrategy: int):
    PlacementSettingAddPriorityCollisionStrategy(builder, priorityCollisionStrategy)

def PlacementSettingEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PlacementSettingEnd(builder)
