# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Plan(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Plan()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlan(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PlanBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # Plan
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Plan
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Plan
    def UniqueHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Plan
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Plan
    def TierPosition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Plan
    def SortOrder(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def PlanStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    PlanStart(builder)

def PlanAddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUint32Slot(0, sourceId, 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    PlanAddSourceId(builder, sourceId)

def PlanAddUniqueHandle(builder: flatbuffers.Builder, uniqueHandle: int):
    builder.PrependUint32Slot(1, uniqueHandle, 0)

def AddUniqueHandle(builder: flatbuffers.Builder, uniqueHandle: int):
    PlanAddUniqueHandle(builder, uniqueHandle)

def PlanAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUint32Slot(2, name, 0)

def AddName(builder: flatbuffers.Builder, name: int):
    PlanAddName(builder, name)

def PlanAddTierPosition(builder: flatbuffers.Builder, tierPosition: int):
    builder.PrependUint32Slot(3, tierPosition, 0)

def AddTierPosition(builder: flatbuffers.Builder, tierPosition: int):
    PlanAddTierPosition(builder, tierPosition)

def PlanAddSortOrder(builder: flatbuffers.Builder, sortOrder: int):
    builder.PrependUint32Slot(4, sortOrder, 0)

def AddSortOrder(builder: flatbuffers.Builder, sortOrder: int):
    PlanAddSortOrder(builder, sortOrder)

def PlanEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PlanEnd(builder)
