from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Plan(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Plan: ...
  @classmethod
  def GetRootAsPlan(cls, buf: bytes, offset: int) -> Plan: ...
  @classmethod
  def PlanBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceId(self) -> int: ...
  def UniqueHandle(self) -> int: ...
  def Name(self) -> int: ...
  def TierPosition(self) -> int: ...
  def SortOrder(self) -> int: ...
def PlanStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def PlanAddSourceId(builder: flatbuffers.Builder, sourceId: int) -> None: ...
def PlanAddUniqueHandle(builder: flatbuffers.Builder, uniqueHandle: int) -> None: ...
def PlanAddName(builder: flatbuffers.Builder, name: int) -> None: ...
def PlanAddTierPosition(builder: flatbuffers.Builder, tierPosition: int) -> None: ...
def PlanAddSortOrder(builder: flatbuffers.Builder, sortOrder: int) -> None: ...
def PlanEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

