# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

class PredicateOp(object):
    unknown = 0
    eq = 1
    neq = 2
    gt = 3
    lt = 4
    gte = 5
    lte = 6
    contains = 7
    in_ = 8
