from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ReverseTrialRule(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ReverseTrialRule: ...
  @classmethod
  def GetRootAsReverseTrialRule(cls, buf: bytes, offset: int) -> ReverseTrialRule: ...
  @classmethod
  def ReverseTrialRuleBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceId(self) -> int: ...
  def Handle(self) -> int: ...
  def PremiumPlanId(self) -> int: ...
  def FallbackPlanId(self) -> int: ...
  def EntitlementsDuringTrial(self, i: int) -> typing.List[int]: ...
  def EntitlementsDuringTrialAsNumpy(self) -> np.ndarray: ...
  def EntitlementsDuringTrialLength(self) -> int: ...
  def EntitlementsDuringTrialIsNone(self) -> bool: ...
  def IsActive(self) -> bool: ...
  def UsageEntitlementHandle(self) -> int: ...
  def UsageLimitValue(self) -> int: ...
def ReverseTrialRuleStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ReverseTrialRuleAddSourceId(builder: flatbuffers.Builder, sourceId: int) -> None: ...
def ReverseTrialRuleAddHandle(builder: flatbuffers.Builder, handle: int) -> None: ...
def ReverseTrialRuleAddPremiumPlanId(builder: flatbuffers.Builder, premiumPlanId: int) -> None: ...
def ReverseTrialRuleAddFallbackPlanId(builder: flatbuffers.Builder, fallbackPlanId: int) -> None: ...
def ReverseTrialRuleAddEntitlementsDuringTrial(builder: flatbuffers.Builder, entitlementsDuringTrial: uoffset) -> None: ...
def ReverseTrialRuleStartEntitlementsDuringTrialVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartEntitlementsDuringTrialVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ReverseTrialRuleAddIsActive(builder: flatbuffers.Builder, isActive: bool) -> None: ...
def ReverseTrialRuleAddUsageEntitlementHandle(builder: flatbuffers.Builder, usageEntitlementHandle: int) -> None: ...
def ReverseTrialRuleAddUsageLimitValue(builder: flatbuffers.Builder, usageLimitValue: int) -> None: ...
def ReverseTrialRuleEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

