# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class ReverseTrialRule(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReverseTrialRule()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReverseTrialRule(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ReverseTrialRuleBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # ReverseTrialRule
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReverseTrialRule
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ReverseTrialRule
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ReverseTrialRule
    def PremiumPlanId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ReverseTrialRule
    def FallbackPlanId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ReverseTrialRule
    def EntitlementsDuringTrial(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ReverseTrialRule
    def EntitlementsDuringTrialAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # ReverseTrialRule
    def EntitlementsDuringTrialLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ReverseTrialRule
    def EntitlementsDuringTrialIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # ReverseTrialRule
    def IsActive(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ReverseTrialRule
    def UsageEntitlementHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ReverseTrialRule
    def UsageLimitValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def ReverseTrialRuleStart(builder: flatbuffers.Builder):
    builder.StartObject(8)

def Start(builder: flatbuffers.Builder):
    ReverseTrialRuleStart(builder)

def ReverseTrialRuleAddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUint32Slot(0, sourceId, 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    ReverseTrialRuleAddSourceId(builder, sourceId)

def ReverseTrialRuleAddHandle(builder: flatbuffers.Builder, handle: int):
    builder.PrependUint32Slot(1, handle, 0)

def AddHandle(builder: flatbuffers.Builder, handle: int):
    ReverseTrialRuleAddHandle(builder, handle)

def ReverseTrialRuleAddPremiumPlanId(builder: flatbuffers.Builder, premiumPlanId: int):
    builder.PrependUint32Slot(2, premiumPlanId, 0)

def AddPremiumPlanId(builder: flatbuffers.Builder, premiumPlanId: int):
    ReverseTrialRuleAddPremiumPlanId(builder, premiumPlanId)

def ReverseTrialRuleAddFallbackPlanId(builder: flatbuffers.Builder, fallbackPlanId: int):
    builder.PrependUint32Slot(3, fallbackPlanId, 0)

def AddFallbackPlanId(builder: flatbuffers.Builder, fallbackPlanId: int):
    ReverseTrialRuleAddFallbackPlanId(builder, fallbackPlanId)

def ReverseTrialRuleAddEntitlementsDuringTrial(builder: flatbuffers.Builder, entitlementsDuringTrial: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(entitlementsDuringTrial), 0)

def AddEntitlementsDuringTrial(builder: flatbuffers.Builder, entitlementsDuringTrial: int):
    ReverseTrialRuleAddEntitlementsDuringTrial(builder, entitlementsDuringTrial)

def ReverseTrialRuleStartEntitlementsDuringTrialVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartEntitlementsDuringTrialVector(builder, numElems: int) -> int:
    return ReverseTrialRuleStartEntitlementsDuringTrialVector(builder, numElems)

def ReverseTrialRuleAddIsActive(builder: flatbuffers.Builder, isActive: bool):
    builder.PrependBoolSlot(5, isActive, 0)

def AddIsActive(builder: flatbuffers.Builder, isActive: bool):
    ReverseTrialRuleAddIsActive(builder, isActive)

def ReverseTrialRuleAddUsageEntitlementHandle(builder: flatbuffers.Builder, usageEntitlementHandle: int):
    builder.PrependUint32Slot(6, usageEntitlementHandle, 0)

def AddUsageEntitlementHandle(builder: flatbuffers.Builder, usageEntitlementHandle: int):
    ReverseTrialRuleAddUsageEntitlementHandle(builder, usageEntitlementHandle)

def ReverseTrialRuleAddUsageLimitValue(builder: flatbuffers.Builder, usageLimitValue: int):
    builder.PrependInt64Slot(7, usageLimitValue, 0)

def AddUsageLimitValue(builder: flatbuffers.Builder, usageLimitValue: int):
    ReverseTrialRuleAddUsageLimitValue(builder, usageLimitValue)

def ReverseTrialRuleEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ReverseTrialRuleEnd(builder)
