from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.RuleTargetKind import RuleTargetKind

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RuleTarget(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RuleTarget: ...
  @classmethod
  def GetRootAsRuleTarget(cls, buf: bytes, offset: int) -> RuleTarget: ...
  @classmethod
  def RuleTargetBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Kind(self) -> typing.Literal[RuleTargetKind.plan, RuleTargetKind.plan_variation, RuleTargetKind.addon, RuleTargetKind.addon_variation]: ...
  def Id(self) -> str | None: ...
def RuleTargetStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RuleTargetAddKind(builder: flatbuffers.Builder, kind: typing.Literal[RuleTargetKind.plan, RuleTargetKind.plan_variation, RuleTargetKind.addon, RuleTargetKind.addon_variation]) -> None: ...
def RuleTargetAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def RuleTargetEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

