from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.ContentOverrideEntry import ContentOverrideEntry
from revturbine.bundle.ContentPromotion import ContentPromotion
from revturbine.bundle.ContentUiPath import ContentUiPath
from revturbine.bundle.EnforcementDefault import EnforcementDefault
from revturbine.bundle.Entitlement import Entitlement
from revturbine.bundle.EntitlementRule import EntitlementRule
from revturbine.bundle.ExtensionRule import ExtensionRule
from revturbine.bundle.FreeTrialRule import FreeTrialRule
from revturbine.bundle.Header import Header
from revturbine.bundle.MessageBlock import MessageBlock
from revturbine.bundle.MeterBinding import MeterBinding
from revturbine.bundle.PersonalizationToken import PersonalizationToken
from revturbine.bundle.Placement import Placement
from revturbine.bundle.PlacementPayload import PlacementPayload
from revturbine.bundle.PlacementSetting import PlacementSetting
from revturbine.bundle.PlacementSlot import PlacementSlot
from revturbine.bundle.Plan import Plan
from revturbine.bundle.Range import Range
from revturbine.bundle.ReverseTrialRule import ReverseTrialRule
from revturbine.bundle.SeatType import SeatType
from revturbine.bundle.Segment import Segment
from revturbine.bundle.SegmentDimension import SegmentDimension
from revturbine.bundle.SlotConfig import SlotConfig
from revturbine.bundle.SurfaceTemplate import SurfaceTemplate

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RuleBundle(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RuleBundle: ...
  @classmethod
  def GetRootAsRuleBundle(cls, buf: bytes, offset: int) -> RuleBundle: ...
  @classmethod
  def RuleBundleBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Header(self) -> Header | None: ...
  def StringPool(self, i: int) -> str: ...
  def StringPoolLength(self) -> int: ...
  def StringPoolIsNone(self) -> bool: ...
  def PredicateFields(self, i: int) -> str: ...
  def PredicateFieldsLength(self) -> int: ...
  def PredicateFieldsIsNone(self) -> bool: ...
  def Plans(self, i: int) -> Plan | None: ...
  def PlansLength(self) -> int: ...
  def PlansIsNone(self) -> bool: ...
  def Entitlements(self, i: int) -> Entitlement | None: ...
  def EntitlementsLength(self) -> int: ...
  def EntitlementsIsNone(self) -> bool: ...
  def EntitlementRules(self, i: int) -> EntitlementRule | None: ...
  def EntitlementRulesLength(self) -> int: ...
  def EntitlementRulesIsNone(self) -> bool: ...
  def Segments(self, i: int) -> Segment | None: ...
  def SegmentsLength(self) -> int: ...
  def SegmentsIsNone(self) -> bool: ...
  def PlacementSlots(self, i: int) -> PlacementSlot | None: ...
  def PlacementSlotsLength(self) -> int: ...
  def PlacementSlotsIsNone(self) -> bool: ...
  def SlotConfigs(self, i: int) -> SlotConfig | None: ...
  def SlotConfigsLength(self) -> int: ...
  def SlotConfigsIsNone(self) -> bool: ...
  def SurfaceTemplates(self, i: int) -> SurfaceTemplate | None: ...
  def SurfaceTemplatesLength(self) -> int: ...
  def SurfaceTemplatesIsNone(self) -> bool: ...
  def Placements(self, i: int) -> Placement | None: ...
  def PlacementsLength(self) -> int: ...
  def PlacementsIsNone(self) -> bool: ...
  def PlacementPayloads(self, i: int) -> PlacementPayload | None: ...
  def PlacementPayloadsLength(self) -> int: ...
  def PlacementPayloadsIsNone(self) -> bool: ...
  def ContentUiPaths(self, i: int) -> ContentUiPath | None: ...
  def ContentUiPathsLength(self) -> int: ...
  def ContentUiPathsIsNone(self) -> bool: ...
  def ContentPromotions(self, i: int) -> ContentPromotion | None: ...
  def ContentPromotionsLength(self) -> int: ...
  def ContentPromotionsIsNone(self) -> bool: ...
  def PersonalizationTokens(self, i: int) -> PersonalizationToken | None: ...
  def PersonalizationTokensLength(self) -> int: ...
  def PersonalizationTokensIsNone(self) -> bool: ...
  def MessageBlocks(self, i: int) -> MessageBlock | None: ...
  def MessageBlocksLength(self) -> int: ...
  def MessageBlocksIsNone(self) -> bool: ...
  def SlotPlacementIndex(self, i: int) -> Range | None: ...
  def SlotPlacementIndexLength(self) -> int: ...
  def SlotPlacementIndexIsNone(self) -> bool: ...
  def ThemeJson(self) -> str | None: ...
  def ContentOverrideKeys(self, i: int) -> str: ...
  def ContentOverrideKeysLength(self) -> int: ...
  def ContentOverrideKeysIsNone(self) -> bool: ...
  def ContentOverrideEntries(self, i: int) -> ContentOverrideEntry | None: ...
  def ContentOverrideEntriesLength(self) -> int: ...
  def ContentOverrideEntriesIsNone(self) -> bool: ...
  def ContentOverrideIndex(self, i: int) -> Range | None: ...
  def ContentOverrideIndexLength(self) -> int: ...
  def ContentOverrideIndexIsNone(self) -> bool: ...
  def CompileTimeSegmentKeys(self, i: int) -> str: ...
  def CompileTimeSegmentKeysLength(self) -> int: ...
  def CompileTimeSegmentKeysIsNone(self) -> bool: ...
  def CompileTimeSegmentMembers(self, i: int) -> typing.List[int]: ...
  def CompileTimeSegmentMembersAsNumpy(self) -> np.ndarray: ...
  def CompileTimeSegmentMembersLength(self) -> int: ...
  def CompileTimeSegmentMembersIsNone(self) -> bool: ...
  def CompileTimeSegmentIndex(self, i: int) -> Range | None: ...
  def CompileTimeSegmentIndexLength(self) -> int: ...
  def CompileTimeSegmentIndexIsNone(self) -> bool: ...
  def ExtensionRules(self, i: int) -> ExtensionRule | None: ...
  def ExtensionRulesLength(self) -> int: ...
  def ExtensionRulesIsNone(self) -> bool: ...
  def SeatTypes(self, i: int) -> SeatType | None: ...
  def SeatTypesLength(self) -> int: ...
  def SeatTypesIsNone(self) -> bool: ...
  def EnforcementDefaults(self, i: int) -> EnforcementDefault | None: ...
  def EnforcementDefaultsLength(self) -> int: ...
  def EnforcementDefaultsIsNone(self) -> bool: ...
  def PlacementSettings(self, i: int) -> PlacementSetting | None: ...
  def PlacementSettingsLength(self) -> int: ...
  def PlacementSettingsIsNone(self) -> bool: ...
  def SegmentDimensions(self, i: int) -> SegmentDimension | None: ...
  def SegmentDimensionsLength(self) -> int: ...
  def SegmentDimensionsIsNone(self) -> bool: ...
  def MeterBindings(self, i: int) -> MeterBinding | None: ...
  def MeterBindingsLength(self) -> int: ...
  def MeterBindingsIsNone(self) -> bool: ...
  def FreeTrialRules(self, i: int) -> FreeTrialRule | None: ...
  def FreeTrialRulesLength(self) -> int: ...
  def FreeTrialRulesIsNone(self) -> bool: ...
  def ReverseTrialRules(self, i: int) -> ReverseTrialRule | None: ...
  def ReverseTrialRulesLength(self) -> int: ...
  def ReverseTrialRulesIsNone(self) -> bool: ...
def RuleBundleStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RuleBundleAddHeader(builder: flatbuffers.Builder, header: uoffset) -> None: ...
def RuleBundleAddStringPool(builder: flatbuffers.Builder, stringPool: uoffset) -> None: ...
def RuleBundleStartStringPoolVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartStringPoolVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddPredicateFields(builder: flatbuffers.Builder, predicateFields: uoffset) -> None: ...
def RuleBundleStartPredicateFieldsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartPredicateFieldsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddPlans(builder: flatbuffers.Builder, plans: uoffset) -> None: ...
def RuleBundleStartPlansVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartPlansVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddEntitlements(builder: flatbuffers.Builder, entitlements: uoffset) -> None: ...
def RuleBundleStartEntitlementsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartEntitlementsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddEntitlementRules(builder: flatbuffers.Builder, entitlementRules: uoffset) -> None: ...
def RuleBundleStartEntitlementRulesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartEntitlementRulesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddSegments(builder: flatbuffers.Builder, segments: uoffset) -> None: ...
def RuleBundleStartSegmentsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSegmentsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddPlacementSlots(builder: flatbuffers.Builder, placementSlots: uoffset) -> None: ...
def RuleBundleStartPlacementSlotsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartPlacementSlotsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddSlotConfigs(builder: flatbuffers.Builder, slotConfigs: uoffset) -> None: ...
def RuleBundleStartSlotConfigsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSlotConfigsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddSurfaceTemplates(builder: flatbuffers.Builder, surfaceTemplates: uoffset) -> None: ...
def RuleBundleStartSurfaceTemplatesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSurfaceTemplatesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddPlacements(builder: flatbuffers.Builder, placements: uoffset) -> None: ...
def RuleBundleStartPlacementsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartPlacementsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddPlacementPayloads(builder: flatbuffers.Builder, placementPayloads: uoffset) -> None: ...
def RuleBundleStartPlacementPayloadsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartPlacementPayloadsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddContentUiPaths(builder: flatbuffers.Builder, contentUiPaths: uoffset) -> None: ...
def RuleBundleStartContentUiPathsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartContentUiPathsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddContentPromotions(builder: flatbuffers.Builder, contentPromotions: uoffset) -> None: ...
def RuleBundleStartContentPromotionsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartContentPromotionsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddPersonalizationTokens(builder: flatbuffers.Builder, personalizationTokens: uoffset) -> None: ...
def RuleBundleStartPersonalizationTokensVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartPersonalizationTokensVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddMessageBlocks(builder: flatbuffers.Builder, messageBlocks: uoffset) -> None: ...
def RuleBundleStartMessageBlocksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartMessageBlocksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddSlotPlacementIndex(builder: flatbuffers.Builder, slotPlacementIndex: uoffset) -> None: ...
def RuleBundleStartSlotPlacementIndexVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSlotPlacementIndexVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddThemeJson(builder: flatbuffers.Builder, themeJson: uoffset) -> None: ...
def RuleBundleAddContentOverrideKeys(builder: flatbuffers.Builder, contentOverrideKeys: uoffset) -> None: ...
def RuleBundleStartContentOverrideKeysVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartContentOverrideKeysVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddContentOverrideEntries(builder: flatbuffers.Builder, contentOverrideEntries: uoffset) -> None: ...
def RuleBundleStartContentOverrideEntriesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartContentOverrideEntriesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddContentOverrideIndex(builder: flatbuffers.Builder, contentOverrideIndex: uoffset) -> None: ...
def RuleBundleStartContentOverrideIndexVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartContentOverrideIndexVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddCompileTimeSegmentKeys(builder: flatbuffers.Builder, compileTimeSegmentKeys: uoffset) -> None: ...
def RuleBundleStartCompileTimeSegmentKeysVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartCompileTimeSegmentKeysVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddCompileTimeSegmentMembers(builder: flatbuffers.Builder, compileTimeSegmentMembers: uoffset) -> None: ...
def RuleBundleStartCompileTimeSegmentMembersVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartCompileTimeSegmentMembersVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddCompileTimeSegmentIndex(builder: flatbuffers.Builder, compileTimeSegmentIndex: uoffset) -> None: ...
def RuleBundleStartCompileTimeSegmentIndexVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartCompileTimeSegmentIndexVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddExtensionRules(builder: flatbuffers.Builder, extensionRules: uoffset) -> None: ...
def RuleBundleStartExtensionRulesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartExtensionRulesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddSeatTypes(builder: flatbuffers.Builder, seatTypes: uoffset) -> None: ...
def RuleBundleStartSeatTypesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSeatTypesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddEnforcementDefaults(builder: flatbuffers.Builder, enforcementDefaults: uoffset) -> None: ...
def RuleBundleStartEnforcementDefaultsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartEnforcementDefaultsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddPlacementSettings(builder: flatbuffers.Builder, placementSettings: uoffset) -> None: ...
def RuleBundleStartPlacementSettingsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartPlacementSettingsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddSegmentDimensions(builder: flatbuffers.Builder, segmentDimensions: uoffset) -> None: ...
def RuleBundleStartSegmentDimensionsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSegmentDimensionsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddMeterBindings(builder: flatbuffers.Builder, meterBindings: uoffset) -> None: ...
def RuleBundleStartMeterBindingsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartMeterBindingsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddFreeTrialRules(builder: flatbuffers.Builder, freeTrialRules: uoffset) -> None: ...
def RuleBundleStartFreeTrialRulesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartFreeTrialRulesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleAddReverseTrialRules(builder: flatbuffers.Builder, reverseTrialRules: uoffset) -> None: ...
def RuleBundleStartReverseTrialRulesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartReverseTrialRulesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RuleBundleEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

