# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

class RuleTargetKind(object):
    plan = 0
    plan_variation = 1
    addon = 2
    addon_variation = 3
