# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from revturbine.bundle.ContentOverrideEntry import ContentOverrideEntry
from revturbine.bundle.ContentPromotion import ContentPromotion
from revturbine.bundle.ContentUiPath import ContentUiPath
from revturbine.bundle.EnforcementDefault import EnforcementDefault
from revturbine.bundle.Entitlement import Entitlement
from revturbine.bundle.EntitlementRule import EntitlementRule
from revturbine.bundle.ExtensionRule import ExtensionRule
from revturbine.bundle.FreeTrialRule import FreeTrialRule
from revturbine.bundle.Header import Header
from revturbine.bundle.MessageBlock import MessageBlock
from revturbine.bundle.MeterBinding import MeterBinding
from revturbine.bundle.PersonalizationToken import PersonalizationToken
from revturbine.bundle.Placement import Placement
from revturbine.bundle.PlacementPayload import PlacementPayload
from revturbine.bundle.PlacementSetting import PlacementSetting
from revturbine.bundle.PlacementSlot import PlacementSlot
from revturbine.bundle.Plan import Plan
from revturbine.bundle.Range import Range
from revturbine.bundle.ReverseTrialRule import ReverseTrialRule
from revturbine.bundle.SeatType import SeatType
from revturbine.bundle.Segment import Segment
from revturbine.bundle.SegmentDimension import SegmentDimension
from revturbine.bundle.SlotConfig import SlotConfig
from revturbine.bundle.SurfaceTemplate import SurfaceTemplate
from typing import Optional
np = import_numpy()

class RuleBundle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RuleBundle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRuleBundle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RuleBundleBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # RuleBundle
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RuleBundle
    def Header(self) -> Optional[Header]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Header()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def StringPool(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # RuleBundle
    def StringPoolLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def StringPoolIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # RuleBundle
    def PredicateFields(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # RuleBundle
    def PredicateFieldsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def PredicateFieldsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # RuleBundle
    def Plans(self, j: int) -> Optional[Plan]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Plan()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def PlansLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def PlansIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # RuleBundle
    def Entitlements(self, j: int) -> Optional[Entitlement]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Entitlement()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def EntitlementsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def EntitlementsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # RuleBundle
    def EntitlementRules(self, j: int) -> Optional[EntitlementRule]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = EntitlementRule()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def EntitlementRulesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def EntitlementRulesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # RuleBundle
    def Segments(self, j: int) -> Optional[Segment]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Segment()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def SegmentsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def SegmentsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # RuleBundle
    def PlacementSlots(self, j: int) -> Optional[PlacementSlot]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = PlacementSlot()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def PlacementSlotsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def PlacementSlotsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # RuleBundle
    def SlotConfigs(self, j: int) -> Optional[SlotConfig]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SlotConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def SlotConfigsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def SlotConfigsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # RuleBundle
    def SurfaceTemplates(self, j: int) -> Optional[SurfaceTemplate]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SurfaceTemplate()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def SurfaceTemplatesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def SurfaceTemplatesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # RuleBundle
    def Placements(self, j: int) -> Optional[Placement]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Placement()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def PlacementsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def PlacementsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # RuleBundle
    def PlacementPayloads(self, j: int) -> Optional[PlacementPayload]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = PlacementPayload()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def PlacementPayloadsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def PlacementPayloadsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

    # RuleBundle
    def ContentUiPaths(self, j: int) -> Optional[ContentUiPath]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ContentUiPath()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def ContentUiPathsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def ContentUiPathsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

    # RuleBundle
    def ContentPromotions(self, j: int) -> Optional[ContentPromotion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ContentPromotion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def ContentPromotionsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def ContentPromotionsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0

    # RuleBundle
    def PersonalizationTokens(self, j: int) -> Optional[PersonalizationToken]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = PersonalizationToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def PersonalizationTokensLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def PersonalizationTokensIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        return o == 0

    # RuleBundle
    def MessageBlocks(self, j: int) -> Optional[MessageBlock]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = MessageBlock()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def MessageBlocksLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def MessageBlocksIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        return o == 0

    # RuleBundle
    def SlotPlacementIndex(self, j: int) -> Optional[Range]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            obj = Range()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def SlotPlacementIndexLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def SlotPlacementIndexIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        return o == 0

    # RuleBundle
    def ThemeJson(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RuleBundle
    def ContentOverrideKeys(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # RuleBundle
    def ContentOverrideKeysLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def ContentOverrideKeysIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        return o == 0

    # RuleBundle
    def ContentOverrideEntries(self, j: int) -> Optional[ContentOverrideEntry]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            obj = ContentOverrideEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def ContentOverrideEntriesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def ContentOverrideEntriesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        return o == 0

    # RuleBundle
    def ContentOverrideIndex(self, j: int) -> Optional[Range]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            obj = Range()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def ContentOverrideIndexLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def ContentOverrideIndexIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        return o == 0

    # RuleBundle
    def CompileTimeSegmentKeys(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # RuleBundle
    def CompileTimeSegmentKeysLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def CompileTimeSegmentKeysIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        return o == 0

    # RuleBundle
    def CompileTimeSegmentMembers(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # RuleBundle
    def CompileTimeSegmentMembersAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # RuleBundle
    def CompileTimeSegmentMembersLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def CompileTimeSegmentMembersIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        return o == 0

    # RuleBundle
    def CompileTimeSegmentIndex(self, j: int) -> Optional[Range]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            obj = Range()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def CompileTimeSegmentIndexLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def CompileTimeSegmentIndexIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        return o == 0

    # RuleBundle
    def ExtensionRules(self, j: int) -> Optional[ExtensionRule]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ExtensionRule()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def ExtensionRulesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def ExtensionRulesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        return o == 0

    # RuleBundle
    def SeatTypes(self, j: int) -> Optional[SeatType]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SeatType()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def SeatTypesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def SeatTypesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        return o == 0

    # RuleBundle
    def EnforcementDefaults(self, j: int) -> Optional[EnforcementDefault]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = EnforcementDefault()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def EnforcementDefaultsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def EnforcementDefaultsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        return o == 0

    # RuleBundle
    def PlacementSettings(self, j: int) -> Optional[PlacementSetting]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = PlacementSetting()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def PlacementSettingsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def PlacementSettingsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        return o == 0

    # RuleBundle
    def SegmentDimensions(self, j: int) -> Optional[SegmentDimension]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SegmentDimension()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def SegmentDimensionsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def SegmentDimensionsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        return o == 0

    # RuleBundle
    def MeterBindings(self, j: int) -> Optional[MeterBinding]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = MeterBinding()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def MeterBindingsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def MeterBindingsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        return o == 0

    # RuleBundle
    def FreeTrialRules(self, j: int) -> Optional[FreeTrialRule]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = FreeTrialRule()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def FreeTrialRulesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def FreeTrialRulesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        return o == 0

    # RuleBundle
    def ReverseTrialRules(self, j: int) -> Optional[ReverseTrialRule]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ReverseTrialRule()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RuleBundle
    def ReverseTrialRulesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RuleBundle
    def ReverseTrialRulesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        return o == 0

def RuleBundleStart(builder: flatbuffers.Builder):
    builder.StartObject(32)

def Start(builder: flatbuffers.Builder):
    RuleBundleStart(builder)

def RuleBundleAddHeader(builder: flatbuffers.Builder, header: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)

def AddHeader(builder: flatbuffers.Builder, header: int):
    RuleBundleAddHeader(builder, header)

def RuleBundleAddStringPool(builder: flatbuffers.Builder, stringPool: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(stringPool), 0)

def AddStringPool(builder: flatbuffers.Builder, stringPool: int):
    RuleBundleAddStringPool(builder, stringPool)

def RuleBundleStartStringPoolVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartStringPoolVector(builder, numElems: int) -> int:
    return RuleBundleStartStringPoolVector(builder, numElems)

def RuleBundleAddPredicateFields(builder: flatbuffers.Builder, predicateFields: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(predicateFields), 0)

def AddPredicateFields(builder: flatbuffers.Builder, predicateFields: int):
    RuleBundleAddPredicateFields(builder, predicateFields)

def RuleBundleStartPredicateFieldsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPredicateFieldsVector(builder, numElems: int) -> int:
    return RuleBundleStartPredicateFieldsVector(builder, numElems)

def RuleBundleAddPlans(builder: flatbuffers.Builder, plans: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(plans), 0)

def AddPlans(builder: flatbuffers.Builder, plans: int):
    RuleBundleAddPlans(builder, plans)

def RuleBundleStartPlansVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPlansVector(builder, numElems: int) -> int:
    return RuleBundleStartPlansVector(builder, numElems)

def RuleBundleAddEntitlements(builder: flatbuffers.Builder, entitlements: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(entitlements), 0)

def AddEntitlements(builder: flatbuffers.Builder, entitlements: int):
    RuleBundleAddEntitlements(builder, entitlements)

def RuleBundleStartEntitlementsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartEntitlementsVector(builder, numElems: int) -> int:
    return RuleBundleStartEntitlementsVector(builder, numElems)

def RuleBundleAddEntitlementRules(builder: flatbuffers.Builder, entitlementRules: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(entitlementRules), 0)

def AddEntitlementRules(builder: flatbuffers.Builder, entitlementRules: int):
    RuleBundleAddEntitlementRules(builder, entitlementRules)

def RuleBundleStartEntitlementRulesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartEntitlementRulesVector(builder, numElems: int) -> int:
    return RuleBundleStartEntitlementRulesVector(builder, numElems)

def RuleBundleAddSegments(builder: flatbuffers.Builder, segments: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(segments), 0)

def AddSegments(builder: flatbuffers.Builder, segments: int):
    RuleBundleAddSegments(builder, segments)

def RuleBundleStartSegmentsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSegmentsVector(builder, numElems: int) -> int:
    return RuleBundleStartSegmentsVector(builder, numElems)

def RuleBundleAddPlacementSlots(builder: flatbuffers.Builder, placementSlots: int):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(placementSlots), 0)

def AddPlacementSlots(builder: flatbuffers.Builder, placementSlots: int):
    RuleBundleAddPlacementSlots(builder, placementSlots)

def RuleBundleStartPlacementSlotsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPlacementSlotsVector(builder, numElems: int) -> int:
    return RuleBundleStartPlacementSlotsVector(builder, numElems)

def RuleBundleAddSlotConfigs(builder: flatbuffers.Builder, slotConfigs: int):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(slotConfigs), 0)

def AddSlotConfigs(builder: flatbuffers.Builder, slotConfigs: int):
    RuleBundleAddSlotConfigs(builder, slotConfigs)

def RuleBundleStartSlotConfigsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSlotConfigsVector(builder, numElems: int) -> int:
    return RuleBundleStartSlotConfigsVector(builder, numElems)

def RuleBundleAddSurfaceTemplates(builder: flatbuffers.Builder, surfaceTemplates: int):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(surfaceTemplates), 0)

def AddSurfaceTemplates(builder: flatbuffers.Builder, surfaceTemplates: int):
    RuleBundleAddSurfaceTemplates(builder, surfaceTemplates)

def RuleBundleStartSurfaceTemplatesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSurfaceTemplatesVector(builder, numElems: int) -> int:
    return RuleBundleStartSurfaceTemplatesVector(builder, numElems)

def RuleBundleAddPlacements(builder: flatbuffers.Builder, placements: int):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(placements), 0)

def AddPlacements(builder: flatbuffers.Builder, placements: int):
    RuleBundleAddPlacements(builder, placements)

def RuleBundleStartPlacementsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPlacementsVector(builder, numElems: int) -> int:
    return RuleBundleStartPlacementsVector(builder, numElems)

def RuleBundleAddPlacementPayloads(builder: flatbuffers.Builder, placementPayloads: int):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(placementPayloads), 0)

def AddPlacementPayloads(builder: flatbuffers.Builder, placementPayloads: int):
    RuleBundleAddPlacementPayloads(builder, placementPayloads)

def RuleBundleStartPlacementPayloadsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPlacementPayloadsVector(builder, numElems: int) -> int:
    return RuleBundleStartPlacementPayloadsVector(builder, numElems)

def RuleBundleAddContentUiPaths(builder: flatbuffers.Builder, contentUiPaths: int):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(contentUiPaths), 0)

def AddContentUiPaths(builder: flatbuffers.Builder, contentUiPaths: int):
    RuleBundleAddContentUiPaths(builder, contentUiPaths)

def RuleBundleStartContentUiPathsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartContentUiPathsVector(builder, numElems: int) -> int:
    return RuleBundleStartContentUiPathsVector(builder, numElems)

def RuleBundleAddContentPromotions(builder: flatbuffers.Builder, contentPromotions: int):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(contentPromotions), 0)

def AddContentPromotions(builder: flatbuffers.Builder, contentPromotions: int):
    RuleBundleAddContentPromotions(builder, contentPromotions)

def RuleBundleStartContentPromotionsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartContentPromotionsVector(builder, numElems: int) -> int:
    return RuleBundleStartContentPromotionsVector(builder, numElems)

def RuleBundleAddPersonalizationTokens(builder: flatbuffers.Builder, personalizationTokens: int):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(personalizationTokens), 0)

def AddPersonalizationTokens(builder: flatbuffers.Builder, personalizationTokens: int):
    RuleBundleAddPersonalizationTokens(builder, personalizationTokens)

def RuleBundleStartPersonalizationTokensVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPersonalizationTokensVector(builder, numElems: int) -> int:
    return RuleBundleStartPersonalizationTokensVector(builder, numElems)

def RuleBundleAddMessageBlocks(builder: flatbuffers.Builder, messageBlocks: int):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(messageBlocks), 0)

def AddMessageBlocks(builder: flatbuffers.Builder, messageBlocks: int):
    RuleBundleAddMessageBlocks(builder, messageBlocks)

def RuleBundleStartMessageBlocksVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartMessageBlocksVector(builder, numElems: int) -> int:
    return RuleBundleStartMessageBlocksVector(builder, numElems)

def RuleBundleAddSlotPlacementIndex(builder: flatbuffers.Builder, slotPlacementIndex: int):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(slotPlacementIndex), 0)

def AddSlotPlacementIndex(builder: flatbuffers.Builder, slotPlacementIndex: int):
    RuleBundleAddSlotPlacementIndex(builder, slotPlacementIndex)

def RuleBundleStartSlotPlacementIndexVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 4)

def StartSlotPlacementIndexVector(builder, numElems: int) -> int:
    return RuleBundleStartSlotPlacementIndexVector(builder, numElems)

def RuleBundleAddThemeJson(builder: flatbuffers.Builder, themeJson: int):
    builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(themeJson), 0)

def AddThemeJson(builder: flatbuffers.Builder, themeJson: int):
    RuleBundleAddThemeJson(builder, themeJson)

def RuleBundleAddContentOverrideKeys(builder: flatbuffers.Builder, contentOverrideKeys: int):
    builder.PrependUOffsetTRelativeSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(contentOverrideKeys), 0)

def AddContentOverrideKeys(builder: flatbuffers.Builder, contentOverrideKeys: int):
    RuleBundleAddContentOverrideKeys(builder, contentOverrideKeys)

def RuleBundleStartContentOverrideKeysVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartContentOverrideKeysVector(builder, numElems: int) -> int:
    return RuleBundleStartContentOverrideKeysVector(builder, numElems)

def RuleBundleAddContentOverrideEntries(builder: flatbuffers.Builder, contentOverrideEntries: int):
    builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(contentOverrideEntries), 0)

def AddContentOverrideEntries(builder: flatbuffers.Builder, contentOverrideEntries: int):
    RuleBundleAddContentOverrideEntries(builder, contentOverrideEntries)

def RuleBundleStartContentOverrideEntriesVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 4)

def StartContentOverrideEntriesVector(builder, numElems: int) -> int:
    return RuleBundleStartContentOverrideEntriesVector(builder, numElems)

def RuleBundleAddContentOverrideIndex(builder: flatbuffers.Builder, contentOverrideIndex: int):
    builder.PrependUOffsetTRelativeSlot(20, flatbuffers.number_types.UOffsetTFlags.py_type(contentOverrideIndex), 0)

def AddContentOverrideIndex(builder: flatbuffers.Builder, contentOverrideIndex: int):
    RuleBundleAddContentOverrideIndex(builder, contentOverrideIndex)

def RuleBundleStartContentOverrideIndexVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 4)

def StartContentOverrideIndexVector(builder, numElems: int) -> int:
    return RuleBundleStartContentOverrideIndexVector(builder, numElems)

def RuleBundleAddCompileTimeSegmentKeys(builder: flatbuffers.Builder, compileTimeSegmentKeys: int):
    builder.PrependUOffsetTRelativeSlot(21, flatbuffers.number_types.UOffsetTFlags.py_type(compileTimeSegmentKeys), 0)

def AddCompileTimeSegmentKeys(builder: flatbuffers.Builder, compileTimeSegmentKeys: int):
    RuleBundleAddCompileTimeSegmentKeys(builder, compileTimeSegmentKeys)

def RuleBundleStartCompileTimeSegmentKeysVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartCompileTimeSegmentKeysVector(builder, numElems: int) -> int:
    return RuleBundleStartCompileTimeSegmentKeysVector(builder, numElems)

def RuleBundleAddCompileTimeSegmentMembers(builder: flatbuffers.Builder, compileTimeSegmentMembers: int):
    builder.PrependUOffsetTRelativeSlot(22, flatbuffers.number_types.UOffsetTFlags.py_type(compileTimeSegmentMembers), 0)

def AddCompileTimeSegmentMembers(builder: flatbuffers.Builder, compileTimeSegmentMembers: int):
    RuleBundleAddCompileTimeSegmentMembers(builder, compileTimeSegmentMembers)

def RuleBundleStartCompileTimeSegmentMembersVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartCompileTimeSegmentMembersVector(builder, numElems: int) -> int:
    return RuleBundleStartCompileTimeSegmentMembersVector(builder, numElems)

def RuleBundleAddCompileTimeSegmentIndex(builder: flatbuffers.Builder, compileTimeSegmentIndex: int):
    builder.PrependUOffsetTRelativeSlot(23, flatbuffers.number_types.UOffsetTFlags.py_type(compileTimeSegmentIndex), 0)

def AddCompileTimeSegmentIndex(builder: flatbuffers.Builder, compileTimeSegmentIndex: int):
    RuleBundleAddCompileTimeSegmentIndex(builder, compileTimeSegmentIndex)

def RuleBundleStartCompileTimeSegmentIndexVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 4)

def StartCompileTimeSegmentIndexVector(builder, numElems: int) -> int:
    return RuleBundleStartCompileTimeSegmentIndexVector(builder, numElems)

def RuleBundleAddExtensionRules(builder: flatbuffers.Builder, extensionRules: int):
    builder.PrependUOffsetTRelativeSlot(24, flatbuffers.number_types.UOffsetTFlags.py_type(extensionRules), 0)

def AddExtensionRules(builder: flatbuffers.Builder, extensionRules: int):
    RuleBundleAddExtensionRules(builder, extensionRules)

def RuleBundleStartExtensionRulesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartExtensionRulesVector(builder, numElems: int) -> int:
    return RuleBundleStartExtensionRulesVector(builder, numElems)

def RuleBundleAddSeatTypes(builder: flatbuffers.Builder, seatTypes: int):
    builder.PrependUOffsetTRelativeSlot(25, flatbuffers.number_types.UOffsetTFlags.py_type(seatTypes), 0)

def AddSeatTypes(builder: flatbuffers.Builder, seatTypes: int):
    RuleBundleAddSeatTypes(builder, seatTypes)

def RuleBundleStartSeatTypesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSeatTypesVector(builder, numElems: int) -> int:
    return RuleBundleStartSeatTypesVector(builder, numElems)

def RuleBundleAddEnforcementDefaults(builder: flatbuffers.Builder, enforcementDefaults: int):
    builder.PrependUOffsetTRelativeSlot(26, flatbuffers.number_types.UOffsetTFlags.py_type(enforcementDefaults), 0)

def AddEnforcementDefaults(builder: flatbuffers.Builder, enforcementDefaults: int):
    RuleBundleAddEnforcementDefaults(builder, enforcementDefaults)

def RuleBundleStartEnforcementDefaultsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartEnforcementDefaultsVector(builder, numElems: int) -> int:
    return RuleBundleStartEnforcementDefaultsVector(builder, numElems)

def RuleBundleAddPlacementSettings(builder: flatbuffers.Builder, placementSettings: int):
    builder.PrependUOffsetTRelativeSlot(27, flatbuffers.number_types.UOffsetTFlags.py_type(placementSettings), 0)

def AddPlacementSettings(builder: flatbuffers.Builder, placementSettings: int):
    RuleBundleAddPlacementSettings(builder, placementSettings)

def RuleBundleStartPlacementSettingsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPlacementSettingsVector(builder, numElems: int) -> int:
    return RuleBundleStartPlacementSettingsVector(builder, numElems)

def RuleBundleAddSegmentDimensions(builder: flatbuffers.Builder, segmentDimensions: int):
    builder.PrependUOffsetTRelativeSlot(28, flatbuffers.number_types.UOffsetTFlags.py_type(segmentDimensions), 0)

def AddSegmentDimensions(builder: flatbuffers.Builder, segmentDimensions: int):
    RuleBundleAddSegmentDimensions(builder, segmentDimensions)

def RuleBundleStartSegmentDimensionsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSegmentDimensionsVector(builder, numElems: int) -> int:
    return RuleBundleStartSegmentDimensionsVector(builder, numElems)

def RuleBundleAddMeterBindings(builder: flatbuffers.Builder, meterBindings: int):
    builder.PrependUOffsetTRelativeSlot(29, flatbuffers.number_types.UOffsetTFlags.py_type(meterBindings), 0)

def AddMeterBindings(builder: flatbuffers.Builder, meterBindings: int):
    RuleBundleAddMeterBindings(builder, meterBindings)

def RuleBundleStartMeterBindingsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartMeterBindingsVector(builder, numElems: int) -> int:
    return RuleBundleStartMeterBindingsVector(builder, numElems)

def RuleBundleAddFreeTrialRules(builder: flatbuffers.Builder, freeTrialRules: int):
    builder.PrependUOffsetTRelativeSlot(30, flatbuffers.number_types.UOffsetTFlags.py_type(freeTrialRules), 0)

def AddFreeTrialRules(builder: flatbuffers.Builder, freeTrialRules: int):
    RuleBundleAddFreeTrialRules(builder, freeTrialRules)

def RuleBundleStartFreeTrialRulesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartFreeTrialRulesVector(builder, numElems: int) -> int:
    return RuleBundleStartFreeTrialRulesVector(builder, numElems)

def RuleBundleAddReverseTrialRules(builder: flatbuffers.Builder, reverseTrialRules: int):
    builder.PrependUOffsetTRelativeSlot(31, flatbuffers.number_types.UOffsetTFlags.py_type(reverseTrialRules), 0)

def AddReverseTrialRules(builder: flatbuffers.Builder, reverseTrialRules: int):
    RuleBundleAddReverseTrialRules(builder, reverseTrialRules)

def RuleBundleStartReverseTrialRulesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartReverseTrialRulesVector(builder, numElems: int) -> int:
    return RuleBundleStartReverseTrialRulesVector(builder, numElems)

def RuleBundleEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RuleBundleEnd(builder)
