# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class SeatsFields(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SeatsFields()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSeatsFields(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SeatsFieldsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # SeatsFields
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SeatsFields
    def IncludedCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # SeatsFields
    def SeatTypeSourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def SeatsFieldsStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    SeatsFieldsStart(builder)

def SeatsFieldsAddIncludedCount(builder: flatbuffers.Builder, includedCount: int):
    builder.PrependInt64Slot(0, includedCount, 0)

def AddIncludedCount(builder: flatbuffers.Builder, includedCount: int):
    SeatsFieldsAddIncludedCount(builder, includedCount)

def SeatsFieldsAddSeatTypeSourceId(builder: flatbuffers.Builder, seatTypeSourceId: int):
    builder.PrependUint32Slot(1, seatTypeSourceId, 0)

def AddSeatTypeSourceId(builder: flatbuffers.Builder, seatTypeSourceId: int):
    SeatsFieldsAddSeatTypeSourceId(builder, seatTypeSourceId)

def SeatsFieldsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return SeatsFieldsEnd(builder)
