from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class SeatsFields(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> SeatsFields: ...
  @classmethod
  def GetRootAsSeatsFields(cls, buf: bytes, offset: int) -> SeatsFields: ...
  @classmethod
  def SeatsFieldsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def IncludedCount(self) -> int: ...
  def SeatTypeSourceId(self) -> int: ...
def SeatsFieldsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def SeatsFieldsAddIncludedCount(builder: flatbuffers.Builder, includedCount: int) -> None: ...
def SeatsFieldsAddSeatTypeSourceId(builder: flatbuffers.Builder, seatTypeSourceId: int) -> None: ...
def SeatsFieldsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

