from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class SeatType(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> SeatType: ...
  @classmethod
  def GetRootAsSeatType(cls, buf: bytes, offset: int) -> SeatType: ...
  @classmethod
  def SeatTypeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Handle(self) -> int: ...
  def Name(self) -> int: ...
  def IsDefault(self) -> bool: ...
  def EntitlementHandles(self, i: int) -> typing.List[int]: ...
  def EntitlementHandlesAsNumpy(self) -> np.ndarray: ...
  def EntitlementHandlesLength(self) -> int: ...
  def EntitlementHandlesIsNone(self) -> bool: ...
def SeatTypeStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def SeatTypeAddHandle(builder: flatbuffers.Builder, handle: int) -> None: ...
def SeatTypeAddName(builder: flatbuffers.Builder, name: int) -> None: ...
def SeatTypeAddIsDefault(builder: flatbuffers.Builder, isDefault: bool) -> None: ...
def SeatTypeAddEntitlementHandles(builder: flatbuffers.Builder, entitlementHandles: uoffset) -> None: ...
def SeatTypeStartEntitlementHandlesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartEntitlementHandlesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def SeatTypeEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

