# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class SeatType(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SeatType()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSeatType(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SeatTypeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # SeatType
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SeatType
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SeatType
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SeatType
    def IsDefault(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SeatType
    def EntitlementHandles(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # SeatType
    def EntitlementHandlesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # SeatType
    def EntitlementHandlesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SeatType
    def EntitlementHandlesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def SeatTypeStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    SeatTypeStart(builder)

def SeatTypeAddHandle(builder: flatbuffers.Builder, handle: int):
    builder.PrependUint32Slot(0, handle, 0)

def AddHandle(builder: flatbuffers.Builder, handle: int):
    SeatTypeAddHandle(builder, handle)

def SeatTypeAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUint32Slot(1, name, 0)

def AddName(builder: flatbuffers.Builder, name: int):
    SeatTypeAddName(builder, name)

def SeatTypeAddIsDefault(builder: flatbuffers.Builder, isDefault: bool):
    builder.PrependBoolSlot(2, isDefault, 0)

def AddIsDefault(builder: flatbuffers.Builder, isDefault: bool):
    SeatTypeAddIsDefault(builder, isDefault)

def SeatTypeAddEntitlementHandles(builder: flatbuffers.Builder, entitlementHandles: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(entitlementHandles), 0)

def AddEntitlementHandles(builder: flatbuffers.Builder, entitlementHandles: int):
    SeatTypeAddEntitlementHandles(builder, entitlementHandles)

def SeatTypeStartEntitlementHandlesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartEntitlementHandlesVector(builder, numElems: int) -> int:
    return SeatTypeStartEntitlementHandlesVector(builder, numElems)

def SeatTypeEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return SeatTypeEnd(builder)
