from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.SegmentCombinator import SegmentCombinator
from revturbine.bundle.SegmentPredicate import SegmentPredicate

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Segment(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Segment: ...
  @classmethod
  def GetRootAsSegment(cls, buf: bytes, offset: int) -> Segment: ...
  @classmethod
  def SegmentBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceId(self) -> int: ...
  def Name(self) -> int: ...
  def Slug(self) -> int: ...
  def Combinator(self) -> typing.Literal[SegmentCombinator.and_, SegmentCombinator.or_]: ...
  def Predicates(self, i: int) -> SegmentPredicate | None: ...
  def PredicatesLength(self) -> int: ...
  def PredicatesIsNone(self) -> bool: ...
  def DimensionId(self) -> int: ...
def SegmentStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def SegmentAddSourceId(builder: flatbuffers.Builder, sourceId: int) -> None: ...
def SegmentAddName(builder: flatbuffers.Builder, name: int) -> None: ...
def SegmentAddSlug(builder: flatbuffers.Builder, slug: int) -> None: ...
def SegmentAddCombinator(builder: flatbuffers.Builder, combinator: typing.Literal[SegmentCombinator.and_, SegmentCombinator.or_]) -> None: ...
def SegmentAddPredicates(builder: flatbuffers.Builder, predicates: uoffset) -> None: ...
def SegmentStartPredicatesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartPredicatesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def SegmentAddDimensionId(builder: flatbuffers.Builder, dimensionId: int) -> None: ...
def SegmentEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

