from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.SegmentChipKind import SegmentChipKind

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class SegmentChip(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def Kind(self) -> typing.Literal[SegmentChipKind.unknown, SegmentChipKind.segment, SegmentChipKind.plan, SegmentChipKind.literal]: ...
  def SegmentIdx(self) -> int: ...
  def PlanIdx(self) -> int: ...
  def Literal(self) -> int: ...

def CreateSegmentChip(builder: flatbuffers.Builder, kind: typing.Literal[SegmentChipKind.unknown, SegmentChipKind.segment, SegmentChipKind.plan, SegmentChipKind.literal], segmentIdx: int, planIdx: int, literal: int) -> uoffset: ...

