# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from revturbine.bundle.SegmentPredicate import SegmentPredicate
from typing import Optional
np = import_numpy()

class Segment(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Segment()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSegment(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SegmentBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # Segment
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Segment
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Segment
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Segment
    def Slug(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Segment
    def Combinator(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Segment
    def Predicates(self, j: int) -> Optional[SegmentPredicate]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            obj = SegmentPredicate()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Segment
    def PredicatesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Segment
    def PredicatesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Segment
    def DimensionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def SegmentStart(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    SegmentStart(builder)

def SegmentAddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUint32Slot(0, sourceId, 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    SegmentAddSourceId(builder, sourceId)

def SegmentAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUint32Slot(1, name, 0)

def AddName(builder: flatbuffers.Builder, name: int):
    SegmentAddName(builder, name)

def SegmentAddSlug(builder: flatbuffers.Builder, slug: int):
    builder.PrependUint32Slot(2, slug, 0)

def AddSlug(builder: flatbuffers.Builder, slug: int):
    SegmentAddSlug(builder, slug)

def SegmentAddCombinator(builder: flatbuffers.Builder, combinator: int):
    builder.PrependUint8Slot(3, combinator, 0)

def AddCombinator(builder: flatbuffers.Builder, combinator: int):
    SegmentAddCombinator(builder, combinator)

def SegmentAddPredicates(builder: flatbuffers.Builder, predicates: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(predicates), 0)

def AddPredicates(builder: flatbuffers.Builder, predicates: int):
    SegmentAddPredicates(builder, predicates)

def SegmentStartPredicatesVector(builder, numElems: int) -> int:
    return builder.StartVector(12, numElems, 4)

def StartPredicatesVector(builder, numElems: int) -> int:
    return SegmentStartPredicatesVector(builder, numElems)

def SegmentAddDimensionId(builder: flatbuffers.Builder, dimensionId: int):
    builder.PrependUint32Slot(5, dimensionId, 0)

def AddDimensionId(builder: flatbuffers.Builder, dimensionId: int):
    SegmentAddDimensionId(builder, dimensionId)

def SegmentEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return SegmentEnd(builder)
