# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class SegmentDimension(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SegmentDimension()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSegmentDimension(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SegmentDimensionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # SegmentDimension
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SegmentDimension
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SegmentDimension
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SegmentDimension
    def Category(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SegmentDimension
    def VisibilityToggle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SegmentDimension
    def SourceType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def SegmentDimensionStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    SegmentDimensionStart(builder)

def SegmentDimensionAddHandle(builder: flatbuffers.Builder, handle: int):
    builder.PrependUint32Slot(0, handle, 0)

def AddHandle(builder: flatbuffers.Builder, handle: int):
    SegmentDimensionAddHandle(builder, handle)

def SegmentDimensionAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUint32Slot(1, name, 0)

def AddName(builder: flatbuffers.Builder, name: int):
    SegmentDimensionAddName(builder, name)

def SegmentDimensionAddCategory(builder: flatbuffers.Builder, category: int):
    builder.PrependUint32Slot(2, category, 0)

def AddCategory(builder: flatbuffers.Builder, category: int):
    SegmentDimensionAddCategory(builder, category)

def SegmentDimensionAddVisibilityToggle(builder: flatbuffers.Builder, visibilityToggle: bool):
    builder.PrependBoolSlot(3, visibilityToggle, 0)

def AddVisibilityToggle(builder: flatbuffers.Builder, visibilityToggle: bool):
    SegmentDimensionAddVisibilityToggle(builder, visibilityToggle)

def SegmentDimensionAddSourceType(builder: flatbuffers.Builder, sourceType: int):
    builder.PrependUint32Slot(4, sourceType, 0)

def AddSourceType(builder: flatbuffers.Builder, sourceType: int):
    SegmentDimensionAddSourceType(builder, sourceType)

def SegmentDimensionEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return SegmentDimensionEnd(builder)
