from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class SegmentDimension(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> SegmentDimension: ...
  @classmethod
  def GetRootAsSegmentDimension(cls, buf: bytes, offset: int) -> SegmentDimension: ...
  @classmethod
  def SegmentDimensionBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Handle(self) -> int: ...
  def Name(self) -> int: ...
  def Category(self) -> int: ...
  def VisibilityToggle(self) -> bool: ...
  def SourceType(self) -> int: ...
def SegmentDimensionStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def SegmentDimensionAddHandle(builder: flatbuffers.Builder, handle: int) -> None: ...
def SegmentDimensionAddName(builder: flatbuffers.Builder, name: int) -> None: ...
def SegmentDimensionAddCategory(builder: flatbuffers.Builder, category: int) -> None: ...
def SegmentDimensionAddVisibilityToggle(builder: flatbuffers.Builder, visibilityToggle: bool) -> None: ...
def SegmentDimensionAddSourceType(builder: flatbuffers.Builder, sourceType: int) -> None: ...
def SegmentDimensionEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

