# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class SegmentPredicate(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 12

    # SegmentPredicate
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SegmentPredicate
    def FieldIdx(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # SegmentPredicate
    def Op(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # SegmentPredicate
    def Value(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateSegmentPredicate(builder, fieldIdx, op, value):
    builder.Prep(4, 12)
    builder.PrependUint32(value)
    builder.Pad(3)
    builder.PrependUint8(op)
    builder.PrependUint32(fieldIdx)
    return builder.Offset()
