# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class SlotConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SlotConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSlotConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SlotConfigBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # SlotConfig
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SlotConfig
    def SlotIdx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SlotConfig
    def Active(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SlotConfig
    def Triggers(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # SlotConfig
    def TriggersAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # SlotConfig
    def TriggersLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SlotConfig
    def TriggersIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def SlotConfigStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    SlotConfigStart(builder)

def SlotConfigAddSlotIdx(builder: flatbuffers.Builder, slotIdx: int):
    builder.PrependUint32Slot(0, slotIdx, 0)

def AddSlotIdx(builder: flatbuffers.Builder, slotIdx: int):
    SlotConfigAddSlotIdx(builder, slotIdx)

def SlotConfigAddActive(builder: flatbuffers.Builder, active: bool):
    builder.PrependBoolSlot(1, active, 0)

def AddActive(builder: flatbuffers.Builder, active: bool):
    SlotConfigAddActive(builder, active)

def SlotConfigAddTriggers(builder: flatbuffers.Builder, triggers: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(triggers), 0)

def AddTriggers(builder: flatbuffers.Builder, triggers: int):
    SlotConfigAddTriggers(builder, triggers)

def SlotConfigStartTriggersVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartTriggersVector(builder, numElems: int) -> int:
    return SlotConfigStartTriggersVector(builder, numElems)

def SlotConfigEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return SlotConfigEnd(builder)
