from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class SlotConfig(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> SlotConfig: ...
  @classmethod
  def GetRootAsSlotConfig(cls, buf: bytes, offset: int) -> SlotConfig: ...
  @classmethod
  def SlotConfigBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SlotIdx(self) -> int: ...
  def Active(self) -> bool: ...
  def Triggers(self, i: int) -> typing.List[int]: ...
  def TriggersAsNumpy(self) -> np.ndarray: ...
  def TriggersLength(self) -> int: ...
  def TriggersIsNone(self) -> bool: ...
def SlotConfigStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def SlotConfigAddSlotIdx(builder: flatbuffers.Builder, slotIdx: int) -> None: ...
def SlotConfigAddActive(builder: flatbuffers.Builder, active: bool) -> None: ...
def SlotConfigAddTriggers(builder: flatbuffers.Builder, triggers: uoffset) -> None: ...
def SlotConfigStartTriggersVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTriggersVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def SlotConfigEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

