# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from revturbine.bundle.PayloadCaps import PayloadCaps
from revturbine.bundle.PayloadSurface import PayloadSurface
from revturbine.bundle.PayloadTarget import PayloadTarget
from typing import Optional
np = import_numpy()

class StudioPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StudioPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStudioPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StudioPayloadBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # StudioPayload
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StudioPayload
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # StudioPayload
    def Target(self) -> Optional[PayloadTarget]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = PayloadTarget()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StudioPayload
    def Surfaces(self, j: int) -> Optional[PayloadSurface]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = PayloadSurface()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StudioPayload
    def SurfacesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StudioPayload
    def SurfacesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # StudioPayload
    def Caps(self) -> Optional[PayloadCaps]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = PayloadCaps()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StudioPayload
    def CreatedAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # StudioPayload
    def RecommendationStrategy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # StudioPayload
    def RecommendationPlanOverride(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # StudioPayload
    def SurfaceSlotIds(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # StudioPayload
    def SurfaceSlotIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # StudioPayload
    def SurfaceSlotIdsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StudioPayload
    def SurfaceSlotIdsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

def StudioPayloadStart(builder: flatbuffers.Builder):
    builder.StartObject(8)

def Start(builder: flatbuffers.Builder):
    StudioPayloadStart(builder)

def StudioPayloadAddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUint32Slot(0, sourceId, 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    StudioPayloadAddSourceId(builder, sourceId)

def StudioPayloadAddTarget(builder: flatbuffers.Builder, target: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(target), 0)

def AddTarget(builder: flatbuffers.Builder, target: int):
    StudioPayloadAddTarget(builder, target)

def StudioPayloadAddSurfaces(builder: flatbuffers.Builder, surfaces: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(surfaces), 0)

def AddSurfaces(builder: flatbuffers.Builder, surfaces: int):
    StudioPayloadAddSurfaces(builder, surfaces)

def StudioPayloadStartSurfacesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSurfacesVector(builder, numElems: int) -> int:
    return StudioPayloadStartSurfacesVector(builder, numElems)

def StudioPayloadAddCaps(builder: flatbuffers.Builder, caps: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(caps), 0)

def AddCaps(builder: flatbuffers.Builder, caps: Any):
    StudioPayloadAddCaps(builder, caps)

def StudioPayloadAddCreatedAt(builder: flatbuffers.Builder, createdAt: int):
    builder.PrependUint32Slot(4, createdAt, 0)

def AddCreatedAt(builder: flatbuffers.Builder, createdAt: int):
    StudioPayloadAddCreatedAt(builder, createdAt)

def StudioPayloadAddRecommendationStrategy(builder: flatbuffers.Builder, recommendationStrategy: int):
    builder.PrependUint8Slot(5, recommendationStrategy, 0)

def AddRecommendationStrategy(builder: flatbuffers.Builder, recommendationStrategy: int):
    StudioPayloadAddRecommendationStrategy(builder, recommendationStrategy)

def StudioPayloadAddRecommendationPlanOverride(builder: flatbuffers.Builder, recommendationPlanOverride: int):
    builder.PrependUint32Slot(6, recommendationPlanOverride, 0)

def AddRecommendationPlanOverride(builder: flatbuffers.Builder, recommendationPlanOverride: int):
    StudioPayloadAddRecommendationPlanOverride(builder, recommendationPlanOverride)

def StudioPayloadAddSurfaceSlotIds(builder: flatbuffers.Builder, surfaceSlotIds: int):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(surfaceSlotIds), 0)

def AddSurfaceSlotIds(builder: flatbuffers.Builder, surfaceSlotIds: int):
    StudioPayloadAddSurfaceSlotIds(builder, surfaceSlotIds)

def StudioPayloadStartSurfaceSlotIdsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSurfaceSlotIdsVector(builder, numElems: int) -> int:
    return StudioPayloadStartSurfaceSlotIdsVector(builder, numElems)

def StudioPayloadEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return StudioPayloadEnd(builder)
