from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.PayloadCaps import PayloadCaps
from revturbine.bundle.PayloadSurface import PayloadSurface
from revturbine.bundle.PayloadTarget import PayloadTarget
from revturbine.bundle.RecommendationStrategy import RecommendationStrategy

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class StudioPayload(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> StudioPayload: ...
  @classmethod
  def GetRootAsStudioPayload(cls, buf: bytes, offset: int) -> StudioPayload: ...
  @classmethod
  def StudioPayloadBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceId(self) -> int: ...
  def Target(self) -> PayloadTarget | None: ...
  def Surfaces(self, i: int) -> PayloadSurface | None: ...
  def SurfacesLength(self) -> int: ...
  def SurfacesIsNone(self) -> bool: ...
  def Caps(self) -> PayloadCaps | None: ...
  def CreatedAt(self) -> int: ...
  def RecommendationStrategy(self) -> typing.Literal[RecommendationStrategy.next_tier_up, RecommendationStrategy.best_value, RecommendationStrategy.custom]: ...
  def RecommendationPlanOverride(self) -> int: ...
  def SurfaceSlotIds(self, i: int) -> typing.List[int]: ...
  def SurfaceSlotIdsAsNumpy(self) -> np.ndarray: ...
  def SurfaceSlotIdsLength(self) -> int: ...
  def SurfaceSlotIdsIsNone(self) -> bool: ...
def StudioPayloadStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def StudioPayloadAddSourceId(builder: flatbuffers.Builder, sourceId: int) -> None: ...
def StudioPayloadAddTarget(builder: flatbuffers.Builder, target: uoffset) -> None: ...
def StudioPayloadAddSurfaces(builder: flatbuffers.Builder, surfaces: uoffset) -> None: ...
def StudioPayloadStartSurfacesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSurfacesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StudioPayloadAddCaps(builder: flatbuffers.Builder, caps: uoffset) -> None: ...
def StudioPayloadAddCreatedAt(builder: flatbuffers.Builder, createdAt: int) -> None: ...
def StudioPayloadAddRecommendationStrategy(builder: flatbuffers.Builder, recommendationStrategy: typing.Literal[RecommendationStrategy.next_tier_up, RecommendationStrategy.best_value, RecommendationStrategy.custom]) -> None: ...
def StudioPayloadAddRecommendationPlanOverride(builder: flatbuffers.Builder, recommendationPlanOverride: int) -> None: ...
def StudioPayloadAddSurfaceSlotIds(builder: flatbuffers.Builder, surfaceSlotIds: uoffset) -> None: ...
def StudioPayloadStartSurfaceSlotIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSurfaceSlotIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StudioPayloadEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

