# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from revturbine.bundle.SurfaceTemplateField import SurfaceTemplateField
from typing import Optional
np = import_numpy()

class SurfaceTemplate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SurfaceTemplate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSurfaceTemplate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SurfaceTemplateBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # SurfaceTemplate
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SurfaceTemplate
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SurfaceTemplate
    def SurfaceType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SurfaceTemplate
    def Fields(self, j: int) -> Optional[SurfaceTemplateField]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            obj = SurfaceTemplateField()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SurfaceTemplate
    def FieldsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SurfaceTemplate
    def FieldsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def SurfaceTemplateStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    SurfaceTemplateStart(builder)

def SurfaceTemplateAddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUint32Slot(0, sourceId, 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    SurfaceTemplateAddSourceId(builder, sourceId)

def SurfaceTemplateAddSurfaceType(builder: flatbuffers.Builder, surfaceType: int):
    builder.PrependUint32Slot(1, surfaceType, 0)

def AddSurfaceType(builder: flatbuffers.Builder, surfaceType: int):
    SurfaceTemplateAddSurfaceType(builder, surfaceType)

def SurfaceTemplateAddFields(builder: flatbuffers.Builder, fields: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(fields), 0)

def AddFields(builder: flatbuffers.Builder, fields: int):
    SurfaceTemplateAddFields(builder, fields)

def SurfaceTemplateStartFieldsVector(builder, numElems: int) -> int:
    return builder.StartVector(12, numElems, 4)

def StartFieldsVector(builder, numElems: int) -> int:
    return SurfaceTemplateStartFieldsVector(builder, numElems)

def SurfaceTemplateEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return SurfaceTemplateEnd(builder)
