from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.SurfaceTemplateField import SurfaceTemplateField

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class SurfaceTemplate(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> SurfaceTemplate: ...
  @classmethod
  def GetRootAsSurfaceTemplate(cls, buf: bytes, offset: int) -> SurfaceTemplate: ...
  @classmethod
  def SurfaceTemplateBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceId(self) -> int: ...
  def SurfaceType(self) -> int: ...
  def Fields(self, i: int) -> SurfaceTemplateField | None: ...
  def FieldsLength(self) -> int: ...
  def FieldsIsNone(self) -> bool: ...
def SurfaceTemplateStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def SurfaceTemplateAddSourceId(builder: flatbuffers.Builder, sourceId: int) -> None: ...
def SurfaceTemplateAddSurfaceType(builder: flatbuffers.Builder, surfaceType: int) -> None: ...
def SurfaceTemplateAddFields(builder: flatbuffers.Builder, fields: uoffset) -> None: ...
def SurfaceTemplateStartFieldsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartFieldsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def SurfaceTemplateEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

