from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class TieredFields(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TieredFields: ...
  @classmethod
  def GetRootAsTieredFields(cls, buf: bytes, offset: int) -> TieredFields: ...
  @classmethod
  def TieredFieldsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TierValue(self) -> int: ...
def TieredFieldsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TieredFieldsAddTierValue(builder: flatbuffers.Builder, tierValue: int) -> None: ...
def TieredFieldsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

