# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

class TokenCategory(object):
    unknown = 0
    user = 1
    plan = 2
    usage = 3
    trial = 4
    billing = 5
    promotion = 6
    custom = 7
