# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

class TokenFormat(object):
    unknown = 0
    string_ = 1
    number = 2
    currency = 3
    percentage = 4
    date = 5
