# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

class TriggerType(object):
    unknown = 0
    surface_render = 1
    entitlement_gate = 2
    usage_threshold = 3
    credit_threshold = 4
    seat_threshold = 5
    trial_started = 6
    trial_progress = 7
    trial_ending = 8
    trial_ended = 9
    trial_converted = 10
    qualifier = 11
