# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

class TypeFields(object):
    NONE = 0
    FeatureFields = 1
    UsageLimitFields = 2
    CreditsFields = 3
    SeatsFields = 4
    TieredFields = 5
