# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

class UiPathActionType(object):
    unknown = 0
    open_checkout_modal = 1
    navigate_to_plans = 2
    open_upgrade_modal = 3
    open_placement = 4
    book_demo = 5
    open_feature_tour = 6
    extend_trial = 7
    switch_billing_period = 8
    custom_url = 9
    dismiss = 10
    contact_sales = 11
    complete_onboarding = 12
    invite_teammate = 13
    refer_friend = 14
    verify_work_email = 15
    update_payment_method = 16
    enable_auto_renewal = 17
    manage_subscription = 18
