# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class UsageLimitFields(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UsageLimitFields()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUsageLimitFields(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def UsageLimitFieldsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x56\x54\x42", size_prefixed=size_prefixed)

    # UsageLimitFields
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UsageLimitFields
    def LimitValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # UsageLimitFields
    def Enforcement(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def UsageLimitFieldsStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    UsageLimitFieldsStart(builder)

def UsageLimitFieldsAddLimitValue(builder: flatbuffers.Builder, limitValue: int):
    builder.PrependInt64Slot(0, limitValue, 0)

def AddLimitValue(builder: flatbuffers.Builder, limitValue: int):
    UsageLimitFieldsAddLimitValue(builder, limitValue)

def UsageLimitFieldsAddEnforcement(builder: flatbuffers.Builder, enforcement: int):
    builder.PrependUint8Slot(1, enforcement, 0)

def AddEnforcement(builder: flatbuffers.Builder, enforcement: int):
    UsageLimitFieldsAddEnforcement(builder, enforcement)

def UsageLimitFieldsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return UsageLimitFieldsEnd(builder)
