# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bundle

class UsageAllocation(object):
    unknown = 0
    account_pool = 1
    per_instance = 2
    per_user = 3
    per_user_pooled = 4
