from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from revturbine.bundle.Enforcement import Enforcement

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class UsageLimitFields(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> UsageLimitFields: ...
  @classmethod
  def GetRootAsUsageLimitFields(cls, buf: bytes, offset: int) -> UsageLimitFields: ...
  @classmethod
  def UsageLimitFieldsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def LimitValue(self) -> int: ...
  def Enforcement(self) -> typing.Literal[Enforcement.unknown, Enforcement.hard_block, Enforcement.soft_warn, Enforcement.throttle, Enforcement.notify, Enforcement.soft_block, Enforcement.degrade, Enforcement.allow_overage]: ...
def UsageLimitFieldsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def UsageLimitFieldsAddLimitValue(builder: flatbuffers.Builder, limitValue: int) -> None: ...
def UsageLimitFieldsAddEnforcement(builder: flatbuffers.Builder, enforcement: typing.Literal[Enforcement.unknown, Enforcement.hard_block, Enforcement.soft_warn, Enforcement.throttle, Enforcement.notify, Enforcement.soft_block, Enforcement.degrade, Enforcement.allow_overage]) -> None: ...
def UsageLimitFieldsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

